-- ============================================================
-- PRE-MIGRATION DATABASE BACKUP
-- Run ONCE before 03_final_er_migration.sql
-- ============================================================

CREATE TABLE BK_PERSON AS SELECT * FROM PERSON;
CREATE TABLE BK_SYSTEM_USER AS SELECT * FROM SYSTEM_USER;
CREATE TABLE BK_EMERGENCY_CONTACT AS SELECT * FROM EMERGENCY_CONTACT;
CREATE TABLE BK_ADOPTER AS SELECT * FROM ADOPTER;
CREATE TABLE BK_OWNER AS SELECT * FROM OWNER;
CREATE TABLE BK_DONOR AS SELECT * FROM DONOR;
CREATE TABLE BK_DONATION AS SELECT * FROM DONATION;
CREATE TABLE BK_INCOME AS SELECT * FROM INCOME;
CREATE TABLE BK_SHELTER AS SELECT * FROM SHELTER;
CREATE TABLE BK_EMPLOYEE AS SELECT * FROM EMPLOYEE;
CREATE TABLE BK_SUPERVISOR AS SELECT * FROM SUPERVISOR;
CREATE TABLE BK_DOCTOR AS SELECT * FROM DOCTOR;
CREATE TABLE BK_MEDICINE AS SELECT * FROM MEDICINE;
CREATE TABLE BK_VACCINATION AS SELECT * FROM VACCINATION;
CREATE TABLE BK_MEDICAL_RECORD AS SELECT * FROM MEDICAL_RECORD;
CREATE TABLE BK_EXPENSE AS SELECT * FROM EXPENSE;

COMMIT;

SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME LIKE 'BK_%'
ORDER BY TABLE_NAME;
