-- !!! DESTRUCTIVE - RUN ONLY WHEN A CLEAN REBUILD IS REQUIRED !!!
-- This file is intentionally excluded from run_all.sql.

BEGIN
  FOR O IN (
    SELECT OBJECT_NAME,OBJECT_TYPE FROM USER_OBJECTS
    WHERE OBJECT_NAME IN (
      'VW_PERSON_BASIC','VW_PERSON_ROLES','VW_ROLE_DIRECTORY','VW_PET_DETAILS','VW_SHELTER_OVERVIEW',
      'VW_RESCUE_DETAILS','VW_ADOPTION_APPLICATIONS','VW_MEDICAL_DETAILS','VW_FINANCE_SUMMARY',
      'VW_SALARY_DETAILS','VW_DASHBOARD_STATS','VW_PERSON_ADDRESS_OBJECT',
      'FN_PERSON_AGE','FN_AVAILABLE_PET_COUNT','PR_CREATE_PERSON','PR_PROCESS_ADOPTION',
      'PR_SUBMIT_ADOPTION','PR_REVIEW_ADOPTION','PR_COMPLETE_ADOPTION',
      'PR_CURSOR_PET_SUMMARY','PR_FIND_PERSON','ADDRESS_TYPE'
    )
    ORDER BY CASE OBJECT_TYPE WHEN 'VIEW' THEN 1 WHEN 'PROCEDURE' THEN 2 WHEN 'FUNCTION' THEN 3 ELSE 4 END
  ) LOOP
    BEGIN EXECUTE IMMEDIATE 'DROP '||O.OBJECT_TYPE||' '||O.OBJECT_NAME; EXCEPTION WHEN OTHERS THEN NULL; END;
  END LOOP;

  FOR T IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN (
    'PERSON','PERSON_ADDRESS','PERSON_PHONE','SYSTEM_USER','EMERGENCY_NO','DOCTOR','VOLUNTEER','SUPERVISOR','ADOPTER','EMPLOYEE','DONOR','OWNER','DOCTOR_TRAINING','RESCUE','SHELTER','PET','LOCAL_PET','GUEST_PET','RESCUE_SHELTER','PET_SHELTER','GUEST_PET_OWNER','VOLUNTEER_RESCUE','MEDICAL_RECORD','MEDICINE','VACCINATION','MEDICAL_RECORD_MEDICINE','MEDICAL_RECORD_VACCINATION','FINANCE','INCOME','EXPENSES','FINANCE_INCOME','FINANCE_EXPENSE','DONATION','OWNER_MEDICINE','EXPENSE_MEDICINE','EXPENSE_VACCINATION','SHELTER_SUPERVISION','ADOPTION_PROCESS','ADOPTION_MANAGEMENT','SALARY'
  )) LOOP
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE '||T.TABLE_NAME||' CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
  END LOOP;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE ADOPTION_ID_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
