-- !!! DESTRUCTIVE - RUN ONLY WHEN A CLEAN REBUILD IS REQUIRED !!!
-- This file is intentionally excluded from run_all.sql.

BEGIN
  FOR O IN (
    SELECT OBJECT_NAME,OBJECT_TYPE FROM USER_OBJECTS
    WHERE OBJECT_NAME IN (
      'VW_PERSON_BASIC','VW_PERSON_ROLES','VW_ROLE_DIRECTORY','VW_PET_DETAILS','VW_SHELTER_OVERVIEW',
      'VW_RESCUE_DETAILS','VW_ADOPTION_APPLICATIONS','VW_MEDICAL_DETAILS','VW_FINANCE_SUMMARY',
      'VW_SALARY_DETAILS','VW_DASHBOARD_STATS','VW_PERSON_ADDRESS_OBJECT',
      'FN_PERSON_AGE','FN_AVAILABLE_PET_COUNT','PR_CREATE_PERSON','PR_PROCESS_ADOPTION',
<<<<<<< HEAD
      'PR_SUBMIT_ADOPTION','PR_REVIEW_ADOPTION','PR_COMPLETE_ADOPTION','PR_MARK_ADOPTED',
      'PR_CURSOR_PET_SUMMARY','PR_FIND_PERSON','PR_OWNER_DIRECTORY',
      'TRG_PERSON_AUTO_ID','TRG_SYSTEM_USER_AUTO_ID','TRG_PET_AUTO_LOCAL_ID',
      'TRG_MEDICAL_RECORD_AUTO_ID','TRG_RESCUE_AUTO_ID','TRG_ADOPTION_AUTO_ID',
      'TRG_AUDIT_LOG_ID','TRG_ADOPTION_STATUS_AUDIT','TRG_ROLE_APP_NO_OWNER',
      'TRG_SALARY_PAYEE_ROLE','PETCARE_ID_CONTEXT','PETCARE_AUDIT_CONTEXT','ADDRESS_TYPE'
=======
      'PR_SUBMIT_ADOPTION','PR_REVIEW_ADOPTION','PR_COMPLETE_ADOPTION',
      'PR_CURSOR_PET_SUMMARY','PR_FIND_PERSON','ADDRESS_TYPE'
>>>>>>> d69b99fc92d668a555103a21fad44187994cefc0
    )
    ORDER BY CASE OBJECT_TYPE WHEN 'VIEW' THEN 1 WHEN 'PROCEDURE' THEN 2 WHEN 'FUNCTION' THEN 3 ELSE 4 END
  ) LOOP
    BEGIN EXECUTE IMMEDIATE 'DROP '||O.OBJECT_TYPE||' '||O.OBJECT_NAME; EXCEPTION WHEN OTHERS THEN NULL; END;
  END LOOP;

  FOR T IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN (
<<<<<<< HEAD
    'PERSON','PERSON_ADDRESS','PERSON_PHONE','SYSTEM_USER_ROLE','ROLE_APPLICATION','SYSTEM_USER','EMERGENCY_NO','DOCTOR','VOLUNTEER','SUPERVISOR','ADOPTER','EMPLOYEE','DONOR','OWNER','DOCTOR_TRAINING','RESCUE','SHELTER','PET','LOCAL_PET','GUEST_PET','RESCUE_SHELTER','PET_SHELTER','GUEST_PET_OWNER','VOLUNTEER_RESCUE','MEDICAL_RECORD','MEDICINE','VACCINATION','MEDICAL_RECORD_MEDICINE','MEDICAL_RECORD_VACCINATION','FINANCE','INCOME','EXPENSES','FINANCE_INCOME','FINANCE_EXPENSE','DONATION','OWNER_MEDICINE','EXPENSE_MEDICINE','EXPENSE_VACCINATION','SHELTER_SUPERVISION','ADOPTION_PROCESS','ADOPTION_MANAGEMENT','SALARY','AUDIT_LOG'
=======
    'PERSON','PERSON_ADDRESS','PERSON_PHONE','SYSTEM_USER','EMERGENCY_NO','DOCTOR','VOLUNTEER','SUPERVISOR','ADOPTER','EMPLOYEE','DONOR','OWNER','DOCTOR_TRAINING','RESCUE','SHELTER','PET','LOCAL_PET','GUEST_PET','RESCUE_SHELTER','PET_SHELTER','GUEST_PET_OWNER','VOLUNTEER_RESCUE','MEDICAL_RECORD','MEDICINE','VACCINATION','MEDICAL_RECORD_MEDICINE','MEDICAL_RECORD_VACCINATION','FINANCE','INCOME','EXPENSES','FINANCE_INCOME','FINANCE_EXPENSE','DONATION','OWNER_MEDICINE','EXPENSE_MEDICINE','EXPENSE_VACCINATION','SHELTER_SUPERVISION','ADOPTION_PROCESS','ADOPTION_MANAGEMENT','SALARY'
>>>>>>> d69b99fc92d668a555103a21fad44187994cefc0
  )) LOOP
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE '||T.TABLE_NAME||' CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
  END LOOP;
END;
/

BEGIN
<<<<<<< HEAD
  FOR S IN (
    SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME IN (
      'PERSON_ID_SEQ','SYSTEM_USER_ID_SEQ','LOCAL_PET_ID_SEQ','GUEST_PET_ID_SEQ',
      'RESCUE_ID_SEQ','MEDICAL_RECORD_ID_SEQ','ADOPTION_ID_SEQ','AUDIT_LOG_SEQ'
    )
  ) LOOP
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE '||S.SEQUENCE_NAME; EXCEPTION WHEN OTHERS THEN NULL; END;
  END LOOP;
=======
  EXECUTE IMMEDIATE 'DROP SEQUENCE ADOPTION_ID_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
>>>>>>> d69b99fc92d668a555103a21fad44187994cefc0
END;
/
