-- Pet Adoption Management System - final ER relational schema
-- Oracle SQL Developer: run with F5 (Run Script).

CREATE TABLE PERSON (
  PERSON_ID VARCHAR2(12) CONSTRAINT PK_PERSON PRIMARY KEY,
  FIRST_NAME VARCHAR2(50) NOT NULL,
  LAST_NAME VARCHAR2(50) NOT NULL,
  DATE_OF_BIRTH DATE,
  GENDER VARCHAR2(10),
  EMAIL VARCHAR2(100),
  CONSTRAINT UK_PERSON_EMAIL UNIQUE (EMAIL),
  CONSTRAINT CK_PERSON_GENDER CHECK (GENDER IN ('MALE','FEMALE','OTHER'))
);

CREATE TABLE PERSON_ADDRESS (
  PERSON_ID VARCHAR2(12) NOT NULL,
  HOUSE_NO VARCHAR2(20) NOT NULL,
  STREET VARCHAR2(100) NOT NULL,
  CITY VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_PERSON_ADDRESS PRIMARY KEY (PERSON_ID,HOUSE_NO,STREET,CITY),
  CONSTRAINT FK_ADDRESS_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE
);

CREATE TABLE PERSON_PHONE (
  PERSON_ID VARCHAR2(12) NOT NULL,
  PHONE VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_PERSON_PHONE PRIMARY KEY (PERSON_ID,PHONE),
  CONSTRAINT FK_PHONE_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE
);

CREATE TABLE SYSTEM_USER (
  USER_ID VARCHAR2(12) CONSTRAINT PK_SYSTEM_USER PRIMARY KEY,
  PERSON_ID VARCHAR2(12) NOT NULL,
  USERNAME VARCHAR2(50) NOT NULL,
  PASSWORD_HASH VARCHAR2(100) NOT NULL,
  USER_ROLE VARCHAR2(20) NOT NULL,
  USER_STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT UK_SYSTEM_USER_PERSON UNIQUE (PERSON_ID),
  CONSTRAINT UK_SYSTEM_USER_USERNAME UNIQUE (USERNAME),
  CONSTRAINT FK_SYSTEM_USER_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID),
  CONSTRAINT CK_SYSTEM_USER_ROLE CHECK (USER_ROLE IN ('ADMIN','SUPERVISOR','EMPLOYEE','DOCTOR','VOLUNTEER','ADOPTER','OWNER','DONOR')),
  CONSTRAINT CK_SYSTEM_USER_STATUS CHECK (USER_STATUS IN ('ACTIVE','INACTIVE'))
);

-- Weak entity: E_NAME is the partial key; PERSON_ID is the owner key.
CREATE TABLE EMERGENCY_NO (
  PERSON_ID VARCHAR2(12) NOT NULL,
  E_NAME VARCHAR2(80) NOT NULL,
  RELATION VARCHAR2(40) NOT NULL,
  PHONE VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_EMERGENCY_NO PRIMARY KEY (PERSON_ID,E_NAME),
  CONSTRAINT FK_EMERGENCY_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE
);

-- PERSON ISA subtype tables.
CREATE TABLE DOCTOR (
  PERSON_ID VARCHAR2(12) CONSTRAINT PK_DOCTOR PRIMARY KEY,
  SALARY NUMBER(12,2),
  SPECIALIZATION VARCHAR2(80),
  CONSTRAINT FK_DOCTOR_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
  CONSTRAINT CK_DOCTOR_SALARY CHECK (SALARY IS NULL OR SALARY >= 0)
);

CREATE TABLE VOLUNTEER (
  PERSON_ID VARCHAR2(12) CONSTRAINT PK_VOLUNTEER PRIMARY KEY,
  SKILL VARCHAR2(100),
  CONSTRAINT FK_VOLUNTEER_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE
);

CREATE TABLE SUPERVISOR (
  PERSON_ID VARCHAR2(12) CONSTRAINT PK_SUPERVISOR PRIMARY KEY,
  CONSTRAINT FK_SUPERVISOR_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE
);

CREATE TABLE ADOPTER (
  PERSON_ID VARCHAR2(12) CONSTRAINT PK_ADOPTER PRIMARY KEY,
  OCCUPATION VARCHAR2(80),
  CONSTRAINT FK_ADOPTER_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE
);

CREATE TABLE EMPLOYEE (
  PERSON_ID VARCHAR2(12) CONSTRAINT PK_EMPLOYEE PRIMARY KEY,
  OCCUPATION VARCHAR2(80),
  HIRE_DATE DATE,
  POSITION VARCHAR2(80),
  SALARY NUMBER(12,2),
  CONSTRAINT FK_EMPLOYEE_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
  CONSTRAINT CK_EMPLOYEE_SALARY CHECK (SALARY IS NULL OR SALARY >= 0)
);

CREATE TABLE DONOR (
  PERSON_ID VARCHAR2(12) CONSTRAINT PK_DONOR PRIMARY KEY,
  DONATION_AMOUNT NUMBER(12,2),
  OCCUPATION VARCHAR2(80),
  CONSTRAINT FK_DONOR_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
  CONSTRAINT CK_DONOR_AMOUNT CHECK (DONATION_AMOUNT IS NULL OR DONATION_AMOUNT >= 0)
);

CREATE TABLE OWNER (
  PERSON_ID VARCHAR2(12) CONSTRAINT PK_OWNER PRIMARY KEY,
  OCCUPATION VARCHAR2(80),
  CONSTRAINT FK_OWNER_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE
);

CREATE TABLE DOCTOR_TRAINING (
  SENIOR_DOCTOR_ID VARCHAR2(12) NOT NULL,
  JUNIOR_DOCTOR_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_DOCTOR_TRAINING PRIMARY KEY (SENIOR_DOCTOR_ID,JUNIOR_DOCTOR_ID),
  CONSTRAINT FK_TRAINING_SENIOR FOREIGN KEY (SENIOR_DOCTOR_ID) REFERENCES DOCTOR(PERSON_ID),
  CONSTRAINT FK_TRAINING_JUNIOR FOREIGN KEY (JUNIOR_DOCTOR_ID) REFERENCES DOCTOR(PERSON_ID),
  CONSTRAINT CK_TRAINING_DIFFERENT CHECK (SENIOR_DOCTOR_ID <> JUNIOR_DOCTOR_ID)
);

CREATE TABLE RESCUE (
  RESCUE_ID VARCHAR2(12) CONSTRAINT PK_RESCUE PRIMARY KEY,
  RESCUE_DATE DATE NOT NULL,
  LOCATION VARCHAR2(150) NOT NULL
);

CREATE TABLE SHELTER (
  SHELTER_ID VARCHAR2(12) CONSTRAINT PK_SHELTER PRIMARY KEY,
  ROOM_TYPE VARCHAR2(60) NOT NULL
);

CREATE TABLE PET (
  PET_ID VARCHAR2(12) CONSTRAINT PK_PET PRIMARY KEY,
  NAME VARCHAR2(60) NOT NULL,
  DOB DATE,
  BREED VARCHAR2(60),
  SPECIES VARCHAR2(40) NOT NULL,
  WEIGHT NUMBER(8,2),
  CONSTRAINT CK_PET_WEIGHT CHECK (WEIGHT IS NULL OR WEIGHT >= 0)
);

-- PET ISA subtype tables.
CREATE TABLE LOCAL_PET (
  PET_ID VARCHAR2(12) CONSTRAINT PK_LOCAL_PET PRIMARY KEY,
  ADOPTION_STATUS VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
  IN_TAKE_DATE DATE NOT NULL,
  CONSTRAINT FK_LOCAL_PET_PET FOREIGN KEY (PET_ID) REFERENCES PET(PET_ID) ON DELETE CASCADE,
  CONSTRAINT CK_LOCAL_PET_STATUS CHECK (ADOPTION_STATUS IN ('AVAILABLE','PENDING','ADOPTED','ON_HOLD'))
);

CREATE TABLE GUEST_PET (
  PET_ID VARCHAR2(12) CONSTRAINT PK_GUEST_PET PRIMARY KEY,
  CHECK_IN_DATE DATE NOT NULL,
  RELEVANT_TIME VARCHAR2(60),
  CONSTRAINT FK_GUEST_PET_PET FOREIGN KEY (PET_ID) REFERENCES PET(PET_ID) ON DELETE CASCADE
);

CREATE TABLE RESCUE_SHELTER (
  RESCUE_ID VARCHAR2(12) CONSTRAINT PK_RESCUE_SHELTER PRIMARY KEY,
  SHELTER_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT FK_RESCUE_SHELTER_RESCUE FOREIGN KEY (RESCUE_ID) REFERENCES RESCUE(RESCUE_ID) ON DELETE CASCADE,
  CONSTRAINT FK_RESCUE_SHELTER_SHELTER FOREIGN KEY (SHELTER_ID) REFERENCES SHELTER(SHELTER_ID)
);

CREATE TABLE PET_SHELTER (
  PET_ID VARCHAR2(12) NOT NULL,
  SHELTER_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_PET_SHELTER PRIMARY KEY (PET_ID,SHELTER_ID),
  CONSTRAINT FK_PET_SHELTER_PET FOREIGN KEY (PET_ID) REFERENCES PET(PET_ID) ON DELETE CASCADE,
  CONSTRAINT FK_PET_SHELTER_SHELTER FOREIGN KEY (SHELTER_ID) REFERENCES SHELTER(SHELTER_ID)
);

CREATE TABLE GUEST_PET_OWNER (
  PET_ID VARCHAR2(12) NOT NULL,
  OWNER_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_GUEST_PET_OWNER PRIMARY KEY (PET_ID,OWNER_ID),
  CONSTRAINT FK_GUEST_OWNER_PET FOREIGN KEY (PET_ID) REFERENCES GUEST_PET(PET_ID) ON DELETE CASCADE,
  CONSTRAINT FK_GUEST_OWNER_OWNER FOREIGN KEY (OWNER_ID) REFERENCES OWNER(PERSON_ID)
);

CREATE TABLE VOLUNTEER_RESCUE (
  VOLUNTEER_ID VARCHAR2(12) NOT NULL,
  RESCUE_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_VOLUNTEER_RESCUE PRIMARY KEY (VOLUNTEER_ID,RESCUE_ID),
  CONSTRAINT FK_VOL_RESCUE_VOLUNTEER FOREIGN KEY (VOLUNTEER_ID) REFERENCES VOLUNTEER(PERSON_ID),
  CONSTRAINT FK_VOL_RESCUE_RESCUE FOREIGN KEY (RESCUE_ID) REFERENCES RESCUE(RESCUE_ID) ON DELETE CASCADE
);

CREATE TABLE MEDICAL_RECORD (
  RECORD_ID VARCHAR2(12) CONSTRAINT PK_MEDICAL_RECORD PRIMARY KEY,
  PET_ID VARCHAR2(12) NOT NULL,
  DIAGNOSIS VARCHAR2(300),
  TREATMENT VARCHAR2(300),
  HEALTH_STATUS VARCHAR2(60) NOT NULL,
  CONSTRAINT FK_MEDICAL_PET FOREIGN KEY (PET_ID) REFERENCES PET(PET_ID)
);

CREATE TABLE MEDICINE (
  MEDICINE_ID VARCHAR2(12) CONSTRAINT PK_MEDICINE PRIMARY KEY,
  DOSAGE VARCHAR2(80),
  PRICE NUMBER(12,2) NOT NULL,
  CONSTRAINT CK_MEDICINE_PRICE CHECK (PRICE >= 0)
);

CREATE TABLE VACCINATION (
  VACCINE_ID VARCHAR2(12) CONSTRAINT PK_VACCINATION PRIMARY KEY,
  VACCINE_NAME VARCHAR2(80) NOT NULL,
  V_DATE DATE NOT NULL,
  NUM_OF_DOSE NUMBER(3) NOT NULL,
  NEXT_DOSE DATE,
  PRICE NUMBER(12,2) NOT NULL,
  CONSTRAINT CK_VACCINATION_DOSE CHECK (NUM_OF_DOSE > 0),
  CONSTRAINT CK_VACCINATION_PRICE CHECK (PRICE >= 0)
);

CREATE TABLE MEDICAL_RECORD_MEDICINE (
  RECORD_ID VARCHAR2(12) NOT NULL,
  MEDICINE_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_MEDICAL_MEDICINE PRIMARY KEY (RECORD_ID,MEDICINE_ID),
  CONSTRAINT FK_MED_MED_RECORD FOREIGN KEY (RECORD_ID) REFERENCES MEDICAL_RECORD(RECORD_ID) ON DELETE CASCADE,
  CONSTRAINT FK_MED_MED_MEDICINE FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(MEDICINE_ID)
);

CREATE TABLE MEDICAL_RECORD_VACCINATION (
  RECORD_ID VARCHAR2(12) NOT NULL,
  VACCINE_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_MEDICAL_VACCINE PRIMARY KEY (RECORD_ID,VACCINE_ID),
  CONSTRAINT FK_MED_VAC_RECORD FOREIGN KEY (RECORD_ID) REFERENCES MEDICAL_RECORD(RECORD_ID) ON DELETE CASCADE,
  CONSTRAINT FK_MED_VAC_VACCINE FOREIGN KEY (VACCINE_ID) REFERENCES VACCINATION(VACCINE_ID)
);

CREATE TABLE FINANCE (
  FINANCE_ID VARCHAR2(12) CONSTRAINT PK_FINANCE PRIMARY KEY,
  CURRENT_BALANCE NUMBER(14,2) DEFAULT 0 NOT NULL,
  CONSTRAINT CK_FINANCE_BALANCE CHECK (CURRENT_BALANCE >= 0)
);

CREATE TABLE INCOME (
  SOURCE_ID VARCHAR2(12) CONSTRAINT PK_INCOME PRIMARY KEY,
  SOURCE_NAME VARCHAR2(100) NOT NULL,
  AMOUNT NUMBER(14,2) NOT NULL,
  CONSTRAINT CK_INCOME_AMOUNT CHECK (AMOUNT >= 0)
);

CREATE TABLE EXPENSES (
  SOURCE_ID VARCHAR2(12) CONSTRAINT PK_EXPENSES PRIMARY KEY,
  SOURCE_NAME VARCHAR2(100) NOT NULL,
  AMOUNT NUMBER(14,2) NOT NULL,
  CONSTRAINT CK_EXPENSES_AMOUNT CHECK (AMOUNT >= 0)
);

CREATE TABLE FINANCE_INCOME (
  FINANCE_ID VARCHAR2(12) NOT NULL,
  SOURCE_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_FINANCE_INCOME PRIMARY KEY (FINANCE_ID,SOURCE_ID),
  CONSTRAINT FK_FIN_INCOME_FINANCE FOREIGN KEY (FINANCE_ID) REFERENCES FINANCE(FINANCE_ID) ON DELETE CASCADE,
  CONSTRAINT FK_FIN_INCOME_SOURCE FOREIGN KEY (SOURCE_ID) REFERENCES INCOME(SOURCE_ID)
);

CREATE TABLE FINANCE_EXPENSE (
  FINANCE_ID VARCHAR2(12) NOT NULL,
  SOURCE_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_FINANCE_EXPENSE PRIMARY KEY (FINANCE_ID,SOURCE_ID),
  CONSTRAINT FK_FIN_EXPENSE_FINANCE FOREIGN KEY (FINANCE_ID) REFERENCES FINANCE(FINANCE_ID) ON DELETE CASCADE,
  CONSTRAINT FK_FIN_EXPENSE_SOURCE FOREIGN KEY (SOURCE_ID) REFERENCES EXPENSES(SOURCE_ID)
);

CREATE TABLE DONATION (
  DONOR_ID VARCHAR2(12) NOT NULL,
  SOURCE_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_DONATION PRIMARY KEY (DONOR_ID,SOURCE_ID),
  CONSTRAINT FK_DONATION_DONOR FOREIGN KEY (DONOR_ID) REFERENCES DONOR(PERSON_ID),
  CONSTRAINT FK_DONATION_INCOME FOREIGN KEY (SOURCE_ID) REFERENCES INCOME(SOURCE_ID)
);

-- Converted, Have and Contains relationships from the final ER.
CREATE TABLE OWNER_MEDICINE (
  OWNER_ID VARCHAR2(12) NOT NULL,
  MEDICINE_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_OWNER_MEDICINE PRIMARY KEY (OWNER_ID,MEDICINE_ID),
  CONSTRAINT FK_OWNER_MED_OWNER FOREIGN KEY (OWNER_ID) REFERENCES OWNER(PERSON_ID),
  CONSTRAINT FK_OWNER_MED_MEDICINE FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(MEDICINE_ID)
);

CREATE TABLE EXPENSE_MEDICINE (
  EXPENSE_SOURCE_ID VARCHAR2(12) NOT NULL,
  MEDICINE_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_EXPENSE_MEDICINE PRIMARY KEY (EXPENSE_SOURCE_ID,MEDICINE_ID),
  CONSTRAINT FK_EXP_MED_EXPENSE FOREIGN KEY (EXPENSE_SOURCE_ID) REFERENCES EXPENSES(SOURCE_ID),
  CONSTRAINT FK_EXP_MED_MEDICINE FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(MEDICINE_ID)
);

CREATE TABLE EXPENSE_VACCINATION (
  EXPENSE_SOURCE_ID VARCHAR2(12) NOT NULL,
  VACCINE_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_EXPENSE_VACCINATION PRIMARY KEY (EXPENSE_SOURCE_ID,VACCINE_ID),
  CONSTRAINT FK_EXP_VAC_EXPENSE FOREIGN KEY (EXPENSE_SOURCE_ID) REFERENCES EXPENSES(SOURCE_ID),
  CONSTRAINT FK_EXP_VAC_VACCINE FOREIGN KEY (VACCINE_ID) REFERENCES VACCINATION(VACCINE_ID)
);

-- Supervisor supervises Shelter.
CREATE TABLE SHELTER_SUPERVISION (
  SUPERVISOR_ID VARCHAR2(12) NOT NULL,
  SHELTER_ID VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_SHELTER_SUPERVISION PRIMARY KEY (SUPERVISOR_ID,SHELTER_ID),
  CONSTRAINT FK_SUPERVISION_SUPERVISOR FOREIGN KEY (SUPERVISOR_ID) REFERENCES SUPERVISOR(PERSON_ID),
  CONSTRAINT FK_SUPERVISION_SHELTER FOREIGN KEY (SHELTER_ID) REFERENCES SHELTER(SHELTER_ID)
);

-- An adopter submits first; a supervisor assigns an employee after approval.

CREATE TABLE ADOPTION_PROCESS (
  ADOPTION_ID VARCHAR2(12) CONSTRAINT PK_ADOPTION_PROCESS PRIMARY KEY,
  ADOPTER_ID VARCHAR2(12) NOT NULL,
  EMPLOYEE_ID VARCHAR2(12),
  LOCAL_PET_ID VARCHAR2(12) NOT NULL,
  APPLY_DATE DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
  CONSTRAINT FK_ADOPTION_ADOPTER FOREIGN KEY (ADOPTER_ID) REFERENCES ADOPTER(PERSON_ID),
  CONSTRAINT FK_ADOPTION_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(PERSON_ID),
  CONSTRAINT FK_ADOPTION_LOCAL_PET FOREIGN KEY (LOCAL_PET_ID) REFERENCES LOCAL_PET(PET_ID),
  CONSTRAINT CK_ADOPTION_STATUS CHECK (STATUS IN ('PENDING','APPROVED','REJECTED','COMPLETED','CANCELLED'))
);

-- Supervisor manages the Adoption Process aggregation.
CREATE TABLE ADOPTION_MANAGEMENT (
  SUPERVISOR_ID VARCHAR2(12) NOT NULL,
  ADOPTION_ID VARCHAR2(12) NOT NULL,
  ASSIGN_DATE DATE NOT NULL,
  SALARY NUMBER(12,2),
  CONSTRAINT PK_ADOPTION_MANAGEMENT PRIMARY KEY (SUPERVISOR_ID,ADOPTION_ID),
  CONSTRAINT UK_ADOPT_MGMT_ADOPTION UNIQUE (ADOPTION_ID),
  CONSTRAINT FK_ADOPT_MGMT_SUPERVISOR FOREIGN KEY (SUPERVISOR_ID) REFERENCES SUPERVISOR(PERSON_ID),
  CONSTRAINT FK_ADOPT_MGMT_ADOPTION FOREIGN KEY (ADOPTION_ID) REFERENCES ADOPTION_PROCESS(ADOPTION_ID) ON DELETE CASCADE,
  CONSTRAINT CK_ADOPT_MGMT_SALARY CHECK (SALARY IS NULL OR SALARY >= 0)
);

-- One payroll row represents one staff payment recorded by a supervisor.
CREATE TABLE SALARY (
  SALARY_ID VARCHAR2(12) CONSTRAINT PK_SALARY PRIMARY KEY,
  RECORDED_BY_SUPERVISOR_ID VARCHAR2(12) NOT NULL,
  PAYEE_ID VARCHAR2(12) NOT NULL,
  PAYEE_ROLE VARCHAR2(20) NOT NULL,
  EXPENSE_SOURCE_ID VARCHAR2(12) NOT NULL,
  SALARY_MONTH VARCHAR2(7) NOT NULL,
  PAYMENT_DATE DATE NOT NULL,
  SALARY_AMOUNT NUMBER(12,2) NOT NULL,
  CONSTRAINT UK_SALARY_EXPENSE UNIQUE (EXPENSE_SOURCE_ID),
  CONSTRAINT FK_SALARY_RECORDED_BY FOREIGN KEY (RECORDED_BY_SUPERVISOR_ID) REFERENCES SUPERVISOR(PERSON_ID),
  CONSTRAINT FK_SALARY_PAYEE FOREIGN KEY (PAYEE_ID) REFERENCES PERSON(PERSON_ID),
  CONSTRAINT FK_SALARY_EXPENSE FOREIGN KEY (EXPENSE_SOURCE_ID) REFERENCES EXPENSES(SOURCE_ID),
  CONSTRAINT CK_SALARY_PAYEE_ROLE CHECK (PAYEE_ROLE IN ('SUPERVISOR','EMPLOYEE','DOCTOR')),
  CONSTRAINT CK_SALARY_AMOUNT CHECK (SALARY_AMOUNT >= 0)
);

CREATE OR REPLACE TRIGGER TRG_SALARY_PAYEE_ROLE
BEFORE INSERT OR UPDATE OF PAYEE_ID,PAYEE_ROLE ON SALARY
FOR EACH ROW
DECLARE
  V_COUNT NUMBER;
BEGIN
  IF :NEW.PAYEE_ROLE='SUPERVISOR' THEN
    SELECT COUNT(*) INTO V_COUNT FROM SUPERVISOR WHERE PERSON_ID=:NEW.PAYEE_ID;
  ELSIF :NEW.PAYEE_ROLE='EMPLOYEE' THEN
    SELECT COUNT(*) INTO V_COUNT FROM EMPLOYEE WHERE PERSON_ID=:NEW.PAYEE_ID;
  ELSE
    SELECT COUNT(*) INTO V_COUNT FROM DOCTOR WHERE PERSON_ID=:NEW.PAYEE_ID;
  END IF;

  IF V_COUNT=0 THEN
    RAISE_APPLICATION_ERROR(-20031,'Selected person does not have the chosen payroll role');
  END IF;
END;
/
