-- ============================================================
-- PET ADOPTION AND MANAGEMENT SYSTEM
-- FINAL FRESH DATABASE SCHEMA
-- 28 tables, arranged in foreign-key dependency order
-- Run this file only in a fresh/empty PET_ADMIN schema.
-- ============================================================

-- ------------------------------------------------------------
-- PERSON
-- ------------------------------------------------------------
CREATE TABLE PERSON 
   (	PERSON_ID VARCHAR2(12),  
	EMAIL VARCHAR2(100),  
	ADDRESS VARCHAR2(200),  
	DATE_OF_BIRTH DATE,  
	FIRST_NAME VARCHAR2(50),  
	LAST_NAME VARCHAR2(50),  
	GENDER VARCHAR2(10),  
	 CONSTRAINT PERSON_PERSON_ID_PK PRIMARY KEY (PERSON_ID) 
, 
	 CONSTRAINT PERSON_EMAIL_UK UNIQUE (EMAIL) 
   ) ;

-- ------------------------------------------------------------
-- PERSON_PHONE
-- ------------------------------------------------------------
CREATE TABLE PERSON_PHONE 
   (	PERSON_ID VARCHAR2(12) NOT NULL,  
	PHONE_NO VARCHAR2(20) NOT NULL,  
	 CONSTRAINT PERSON_PHONE_PK PRIMARY KEY (PERSON_ID, PHONE_NO) 
, 
	 CONSTRAINT PERSON_PHONE_PERSON_FK FOREIGN KEY (PERSON_ID) 
	  REFERENCES PERSON (PERSON_ID)
   ) ;

-- ------------------------------------------------------------
-- EMERGENCY_CONTACT
-- ------------------------------------------------------------
CREATE TABLE EMERGENCY_CONTACT 
   (	PERSON_ID VARCHAR2(12) NOT NULL,  
	CONTACT_NAME VARCHAR2(100) NOT NULL,  
	RELATIONSHIP VARCHAR2(40),  
	PHONE_NO VARCHAR2(20) NOT NULL,  
	CONTACT_NO NUMBER(4,0) NOT NULL,  
	 CONSTRAINT EMERGENCY_CONTACT_PK PRIMARY KEY (PERSON_ID, CONTACT_NO) 
, 
	 CONSTRAINT EMERGENCY_CONTACT_PERSON_FK FOREIGN KEY (PERSON_ID) 
	  REFERENCES PERSON (PERSON_ID)
   ) ;

-- ------------------------------------------------------------
-- EMPLOYEE
-- ------------------------------------------------------------
CREATE TABLE EMPLOYEE 
   (	EMPLOYEE_ID VARCHAR2(12),  
	HIRE_DATE DATE NOT NULL,  
	JOB_TITLE VARCHAR2(50) NOT NULL,  
	EMPLOYMENT_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',  
	SALARY NUMBER(12,2),  
	 CONSTRAINT EMPLOYEE_STATUS_CK CHECK (EMPLOYMENT_STATUS IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE')),  
	 CONSTRAINT EMPLOYEE_EMPLOYEE_ID_PK PRIMARY KEY (EMPLOYEE_ID) 
, 
	 CONSTRAINT EMPLOYEE_EMPLOYEE_ID_FK FOREIGN KEY (EMPLOYEE_ID) 
	  REFERENCES PERSON (PERSON_ID)
   ) ;

-- ------------------------------------------------------------
-- SUPERVISOR
-- ------------------------------------------------------------
CREATE TABLE SUPERVISOR 
   (	SUPERVISOR_ID VARCHAR2(12),  
	ASSIGNED_DATE DATE NOT NULL,  
	SALARY NUMBER(12,2),  
	 CONSTRAINT SUPERVISOR_SUPERVISOR_ID_PK PRIMARY KEY (SUPERVISOR_ID) 
, 
	 CONSTRAINT SUPERVISOR_SUPERVISOR_ID_FK FOREIGN KEY (SUPERVISOR_ID) 
	  REFERENCES EMPLOYEE (EMPLOYEE_ID)
   ) ;

-- ------------------------------------------------------------
-- DOCTOR
-- ------------------------------------------------------------
CREATE TABLE DOCTOR 
   (	DOCTOR_ID VARCHAR2(12),  
	LICENSE_NO VARCHAR2(30) NOT NULL,  
	SPECIALIZATION VARCHAR2(60),  
	SALARY NUMBER(12,2),  
	 CONSTRAINT DOCTOR_DOCTOR_ID_PK PRIMARY KEY (DOCTOR_ID) 
, 
	 CONSTRAINT DOCTOR_LICENSE_NO_UK UNIQUE (LICENSE_NO) 
, 
	 CONSTRAINT DOCTOR_DOCTOR_ID_FK FOREIGN KEY (DOCTOR_ID) 
	  REFERENCES EMPLOYEE (EMPLOYEE_ID)
   ) ;

-- ------------------------------------------------------------
-- VOLUNTEER
-- ------------------------------------------------------------
CREATE TABLE VOLUNTEER 
   (	VOLUNTEER_ID VARCHAR2(12),  
	JOIN_DATE DATE NOT NULL,  
	AVAILABILITY VARCHAR2(20) DEFAULT 'AVAILABLE',  
	 CONSTRAINT VOLUNTEER_AVAILABILITY_CK CHECK (AVAILABILITY IN ('AVAILABLE', 'UNAVAILABLE', 'ON_DUTY')),  
	 CONSTRAINT VOLUNTEER_VOLUNTEER_ID_PK PRIMARY KEY (VOLUNTEER_ID) 
, 
	 CONSTRAINT VOLUNTEER_VOLUNTEER_ID_FK FOREIGN KEY (VOLUNTEER_ID) 
	  REFERENCES PERSON (PERSON_ID)
   ) ;

-- ------------------------------------------------------------
-- OWNER
-- ------------------------------------------------------------
CREATE TABLE OWNER 
   (	OWNER_ID VARCHAR2(12),  
	OCCUPATION VARCHAR2(60) NOT NULL,  
	 CONSTRAINT OWNER_OWNER_ID_PK PRIMARY KEY (OWNER_ID) 
, 
	 CONSTRAINT OWNER_OWNER_ID_FK FOREIGN KEY (OWNER_ID) 
	  REFERENCES PERSON (PERSON_ID)
   ) ;

-- ------------------------------------------------------------
-- ADOPTER
-- ------------------------------------------------------------
CREATE TABLE ADOPTER 
   (	ADOPTER_ID VARCHAR2(12),  
	REGISTRATION_DATE DATE NOT NULL,  
	OCCUPATION VARCHAR2(60),  
	ADOPTER_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',  
	 CONSTRAINT ADOPTER_STATUS_CK CHECK ( 
            ADOPTER_STATUS IN ('ACTIVE', 'INACTIVE', 'BLOCKED')
        ), 
	 CONSTRAINT ADOPTER_ADOPTER_ID_PK PRIMARY KEY (ADOPTER_ID) 
, 
	 CONSTRAINT ADOPTER_ADOPTER_ID_FK FOREIGN KEY (ADOPTER_ID) 
	  REFERENCES PERSON (PERSON_ID)
   ) ;

-- ------------------------------------------------------------
-- DONOR
-- ------------------------------------------------------------
CREATE TABLE DONOR 
   (	DONOR_ID VARCHAR2(12),  
	REGISTRATION_DATE DATE NOT NULL,  
	DONOR_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',  
	OCCUPATION VARCHAR2(60),  
	AMOUNT NUMBER(12,2),  
	 CONSTRAINT DONOR_STATUS_CK CHECK ( 
            DONOR_STATUS IN ('ACTIVE', 'INACTIVE', 'BLOCKED')
        ), 
	 CONSTRAINT DONOR_DONOR_ID_PK PRIMARY KEY (DONOR_ID) 
, 
	 CONSTRAINT DONOR_DONOR_ID_FK FOREIGN KEY (DONOR_ID) 
	  REFERENCES PERSON (PERSON_ID)
   ) ;

-- ------------------------------------------------------------
-- SYSTEM_USER
-- ------------------------------------------------------------
CREATE TABLE SYSTEM_USER 
   (	USER_ID VARCHAR2(12),  
	PERSON_ID VARCHAR2(12) NOT NULL,  
	USERNAME VARCHAR2(50) NOT NULL,  
	PASSWORD_HASH VARCHAR2(255) NOT NULL,  
	USER_ROLE VARCHAR2(20) NOT NULL,  
	USER_STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,  
	 CONSTRAINT SYSTEM_USER_ROLE_CK CHECK ( 
            USER_ROLE IN (
                'ADMIN',
                'SUPERVISOR',
                'DOCTOR',
                'EMPLOYEE'
            )
        ), 
	 CONSTRAINT SYSTEM_USER_STATUS_CK CHECK ( 
            USER_STATUS IN (
                'ACTIVE',
                'INACTIVE',
                'BLOCKED'
            )
        ), 
	 CONSTRAINT SYSTEM_USER_PK PRIMARY KEY (USER_ID) 
, 
	 CONSTRAINT SYSTEM_USER_PERSON_UK UNIQUE (PERSON_ID) 
, 
	 CONSTRAINT SYSTEM_USER_USERNAME_UK UNIQUE (USERNAME) 
, 
	 CONSTRAINT SYSTEM_USER_PERSON_FK FOREIGN KEY (PERSON_ID) 
	  REFERENCES PERSON (PERSON_ID)
   ) ;

-- ------------------------------------------------------------
-- INCOME
-- ------------------------------------------------------------
CREATE TABLE INCOME 
   (	INCOME_ID VARCHAR2(12),  
	INCOME_DATE DATE NOT NULL,  
	AMOUNT NUMBER(12,2) NOT NULL,  
	INCOME_DESCRIPTION VARCHAR2(200),  
	INCOME_STATUS VARCHAR2(20) DEFAULT 'RECEIVED',  
	 CONSTRAINT INCOME_AMOUNT_CK CHECK (AMOUNT > 0),  
	 CONSTRAINT INCOME_STATUS_CK CHECK ( 
            INCOME_STATUS IN ('PENDING', 'RECEIVED', 'REFUNDED')
        ), 
	 CONSTRAINT INCOME_INCOME_ID_PK PRIMARY KEY (INCOME_ID) 
   ) ;

-- ------------------------------------------------------------
-- EXPENSE
-- ------------------------------------------------------------
CREATE TABLE EXPENSE 
   (	EXPENSE_ID VARCHAR2(12),  
	EXPENSE_DATE DATE NOT NULL,  
	SOURCE_NAME VARCHAR2(30) NOT NULL,  
	AMOUNT NUMBER(12,2) NOT NULL,  
	EXPENSE_DESCRIPTION VARCHAR2(200),  
	EXPENSE_STATUS VARCHAR2(20) DEFAULT 'PAID',  
	 CONSTRAINT EXPENSE_AMOUNT_CK CHECK (AMOUNT > 0),  
	 CONSTRAINT EXPENSE_TYPE_CK CHECK (SOURCE_NAME='SALARY' OR SOURCE_NAME='MEDICAL' OR SOURCE_NAME='FOOD' OR SOURCE_NAME='SHELTER' OR SOURCE_NAME='RESCUE' OR SOURCE_NAME='OTHER'),  
	 CONSTRAINT EXPENSE_STATUS_CK CHECK ( 
            EXPENSE_STATUS IN ('PENDING', 'PAID', 'CANCELLED')
        ), 
	 CONSTRAINT EXPENSE_EXPENSE_ID_PK PRIMARY KEY (EXPENSE_ID) 
   ) ;

-- ------------------------------------------------------------
-- SHELTER
-- ------------------------------------------------------------
CREATE TABLE SHELTER 
   (	SHELTER_ID VARCHAR2(12),  
	CAPACITY NUMBER(6,0) NOT NULL,  
	SUPERVISOR_ID VARCHAR2(12),  
	SHELTER_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',  
	ROOM_TYPE VARCHAR2(40) NOT NULL,  
	 CONSTRAINT SHELTER_CAPACITY_CK CHECK (CAPACITY > 0),  
	 CONSTRAINT SHELTER_STATUS_CK CHECK ( 
            SHELTER_STATUS IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE')
        ), 
	 CONSTRAINT SHELTER_SHELTER_ID_PK PRIMARY KEY (SHELTER_ID) 
, 
	 CONSTRAINT SHELTER_SUPERVISOR_ID_FK FOREIGN KEY (SUPERVISOR_ID) 
	  REFERENCES SUPERVISOR (SUPERVISOR_ID)
   ) ;

-- ------------------------------------------------------------
-- PET
-- ------------------------------------------------------------
CREATE TABLE PET 
   (	PET_ID VARCHAR2(12),  
	PET_NAME VARCHAR2(80) NOT NULL,  
	SPECIES VARCHAR2(40) NOT NULL,  
	BREED VARCHAR2(60),  
	GENDER VARCHAR2(10),  
	DATE_OF_BIRTH DATE,  
	COLOR VARCHAR2(40),  
	WEIGHT NUMBER(7,2),  
	PET_STATUS VARCHAR2(20) DEFAULT 'AVAILABLE',  
	IMAGE_PATH VARCHAR2(255),  
	OWNER_ID VARCHAR2(12),  
	 CONSTRAINT PET_GENDER_CK CHECK (GENDER IN ('MALE', 'FEMALE', 'UNKNOWN')),  
	 CONSTRAINT PET_WEIGHT_CK CHECK (WEIGHT > 0),  
	 CONSTRAINT PET_STATUS_CK CHECK ( 
            PET_STATUS IN
            ('AVAILABLE', 'ADOPTED', 'RESCUED', 'TREATMENT', 'GUEST')
        ), 
	 CONSTRAINT PET_PET_ID_PK PRIMARY KEY (PET_ID) 
, 
	 CONSTRAINT PET_OWNER_ID_FK FOREIGN KEY (OWNER_ID) 
	  REFERENCES OWNER (OWNER_ID)
   ) ;

-- ------------------------------------------------------------
-- LOCAL_PET
-- ------------------------------------------------------------
CREATE TABLE LOCAL_PET 
   (	LOCAL_PET_ID VARCHAR2(12),  
	INTAKE_DATE DATE NOT NULL,  
	ADOPTION_STATUS VARCHAR2(20) DEFAULT 'AVAILABLE',  
	 CONSTRAINT LOCAL_PET_ADOPTION_STATUS_CK CHECK ( 
            ADOPTION_STATUS IN
            ('AVAILABLE', 'PENDING', 'ADOPTED', 'NOT_AVAILABLE')
        ), 
	 CONSTRAINT LOCAL_PET_ID_PK PRIMARY KEY (LOCAL_PET_ID) 
, 
	 CONSTRAINT LOCAL_PET_ID_FK FOREIGN KEY (LOCAL_PET_ID) 
	  REFERENCES PET (PET_ID)
   ) ;

-- ------------------------------------------------------------
-- GUEST_PET
-- ------------------------------------------------------------
CREATE TABLE GUEST_PET 
   (	GUEST_PET_ID VARCHAR2(12),  
	CHECK_IN_DATE DATE NOT NULL,  
	CHECK_OUT_DATE DATE,  
	GUEST_STATUS VARCHAR2(20) DEFAULT 'CHECKED_IN',  
	OWNER_ID VARCHAR2(12),  
	 CONSTRAINT GUEST_PET_STATUS_CK CHECK ( 
            GUEST_STATUS IN
            ('CHECKED_IN', 'CHECKED_OUT', 'EXTENDED')
        ), 
	 CONSTRAINT GUEST_PET_DATES_CK CHECK ( 
            CHECK_OUT_DATE IS NULL
            OR CHECK_OUT_DATE >= CHECK_IN_DATE
        ), 
	 CONSTRAINT GUEST_PET_ID_PK PRIMARY KEY (GUEST_PET_ID) 
, 
	 CONSTRAINT GUEST_PET_ID_FK FOREIGN KEY (GUEST_PET_ID) 
	  REFERENCES PET (PET_ID),  
	 CONSTRAINT GUEST_PET_OWNER_FK FOREIGN KEY (OWNER_ID) 
	  REFERENCES OWNER (OWNER_ID)
   ) ;

-- ------------------------------------------------------------
-- RESCUE
-- ------------------------------------------------------------
CREATE TABLE RESCUE 
   (	RESCUE_ID VARCHAR2(12),  
	RESCUE_LOCATION VARCHAR2(200) NOT NULL,  
	RESCUE_DATE DATE NOT NULL,  
	RESCUE_DESCRIPTION VARCHAR2(300),  
	RESCUE_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',  
	 CONSTRAINT RESCUE_STATUS_CK CHECK ( 
            RESCUE_STATUS IN
            ('ACTIVE', 'COMPLETED', 'CANCELLED')
        ), 
	 CONSTRAINT RESCUE_RESCUE_ID_PK PRIMARY KEY (RESCUE_ID) 
   ) ;

-- ------------------------------------------------------------
-- RESCUE_PET
-- ------------------------------------------------------------
CREATE TABLE RESCUE_PET 
   (	RESCUE_ID VARCHAR2(12),  
	PET_ID VARCHAR2(12),  
	 CONSTRAINT RESCUE_PET_PK PRIMARY KEY (RESCUE_ID, PET_ID) 
, 
	 CONSTRAINT RESCUE_PET_RESCUE_FK FOREIGN KEY (RESCUE_ID) 
	  REFERENCES RESCUE (RESCUE_ID),  
	 CONSTRAINT RESCUE_PET_PET_FK FOREIGN KEY (PET_ID) 
	  REFERENCES PET (PET_ID)
   ) ;

-- ------------------------------------------------------------
-- RESCUE_VOLUNTEER
-- ------------------------------------------------------------
CREATE TABLE RESCUE_VOLUNTEER 
   (	RESCUE_ID VARCHAR2(12),  
	VOLUNTEER_ID VARCHAR2(12),  
	PARTICIPATION_ROLE VARCHAR2(60),  
	PARTICIPATION_DATE DATE NOT NULL,  
	 CONSTRAINT RESCUE_VOLUNTEER_PK PRIMARY KEY (RESCUE_ID, VOLUNTEER_ID) 
, 
	 CONSTRAINT RESCUE_VOLUNTEER_RESCUE_FK FOREIGN KEY (RESCUE_ID) 
	  REFERENCES RESCUE (RESCUE_ID),  
	 CONSTRAINT RESCUE_VOLUNTEER_VOLUNTEER_FK FOREIGN KEY (VOLUNTEER_ID) 
	  REFERENCES VOLUNTEER (VOLUNTEER_ID)
   ) ;

-- ------------------------------------------------------------
-- MEDICAL_RECORD
-- ------------------------------------------------------------
CREATE TABLE MEDICAL_RECORD 
   (	RECORD_ID VARCHAR2(12),  
	PET_ID VARCHAR2(12) NOT NULL,  
	DOCTOR_ID VARCHAR2(12) NOT NULL,  
	RECORD_DATE DATE NOT NULL,  
	DIAGNOSIS VARCHAR2(300),  
	TREATMENT VARCHAR2(300),  
	HEALTH_STATUS VARCHAR2(400),  
	 CONSTRAINT MEDICAL_RECORD_ID_PK PRIMARY KEY (RECORD_ID) 
, 
	 CONSTRAINT MEDICAL_RECORD_PET_FK FOREIGN KEY (PET_ID) 
	  REFERENCES PET (PET_ID),  
	 CONSTRAINT MEDICAL_RECORD_DOCTOR_FK FOREIGN KEY (DOCTOR_ID) 
	  REFERENCES DOCTOR (DOCTOR_ID)
   ) ;

-- ------------------------------------------------------------
-- MEDICINE
-- ------------------------------------------------------------
CREATE TABLE MEDICINE 
   (	MEDICINE_ID VARCHAR2(12),  
	MEDICINE_NAME VARCHAR2(100) NOT NULL,  
	MEDICINE_TYPE VARCHAR2(40),  
	PRICE NUMBER(12,2) NOT NULL,  
	STOCK_QUANTITY NUMBER(8,0) DEFAULT 0,  
	EXPIRY_DATE DATE,  
	 CONSTRAINT MEDICINE_UNIT_PRICE_CK CHECK (PRICE>=0),  
	 CONSTRAINT MEDICINE_STOCK_CK CHECK (STOCK_QUANTITY >= 0),  
	 CONSTRAINT MEDICINE_ID_PK PRIMARY KEY (MEDICINE_ID) 
   ) ;

-- ------------------------------------------------------------
-- PRESCRIPTION
-- ------------------------------------------------------------
CREATE TABLE PRESCRIPTION 
   (	RECORD_ID VARCHAR2(12),  
	MEDICINE_ID VARCHAR2(12),  
	DOSAGE VARCHAR2(60) NOT NULL,  
	FREQUENCY VARCHAR2(60),  
	DURATION_DAYS NUMBER(5,0),  
	INSTRUCTIONS VARCHAR2(200),  
	 CONSTRAINT PRESCRIPTION_DURATION_CK CHECK ( 
            DURATION_DAYS IS NULL
            OR DURATION_DAYS > 0
        ), 
	 CONSTRAINT PRESCRIPTION_PK PRIMARY KEY (RECORD_ID, MEDICINE_ID) 
, 
	 CONSTRAINT PRESCRIPTION_RECORD_FK FOREIGN KEY (RECORD_ID) 
	  REFERENCES MEDICAL_RECORD (RECORD_ID),  
	 CONSTRAINT PRESCRIPTION_MEDICINE_FK FOREIGN KEY (MEDICINE_ID) 
	  REFERENCES MEDICINE (MEDICINE_ID)
   ) ;

-- ------------------------------------------------------------
-- VACCINATION
-- ------------------------------------------------------------
CREATE TABLE VACCINATION 
   (	VACCINATION_ID VARCHAR2(12),  
	RECORD_ID VARCHAR2(12) NOT NULL,  
	VACCINE_NAME VARCHAR2(100) NOT NULL,  
	VACCINATION_DATE DATE NOT NULL,  
	NEXT_DUE_DATE DATE,  
	VACCINATION_STATUS VARCHAR2(20) DEFAULT 'COMPLETED',  
	VACCINE_PRICE NUMBER(12,2),  
	 CONSTRAINT VACCINATION_STATUS_CK CHECK ( 
            VACCINATION_STATUS IN
            ('SCHEDULED', 'COMPLETED', 'MISSED', 'CANCELLED')
        ), 
	 CONSTRAINT VACCINATION_DATES_CK CHECK ( 
            NEXT_DUE_DATE IS NULL
            OR NEXT_DUE_DATE >= VACCINATION_DATE
        ), 
	 CONSTRAINT VACCINATION_ID_PK PRIMARY KEY (VACCINATION_ID) 
, 
	 CONSTRAINT VACCINATION_RECORD_FK FOREIGN KEY (RECORD_ID) 
	  REFERENCES MEDICAL_RECORD (RECORD_ID)
   ) ;

-- ------------------------------------------------------------
-- ADOPTION_PROCESS
-- ------------------------------------------------------------
CREATE TABLE ADOPTION_PROCESS 
   (	ADOPTION_ID VARCHAR2(12),  
	ADOPTER_ID VARCHAR2(12) NOT NULL,  
	PET_ID VARCHAR2(12) NOT NULL,  
	EMPLOYEE_ID VARCHAR2(12),  
	APPLICATION_DATE DATE NOT NULL,  
	COMPLETION_DATE DATE,  
	ADOPTION_STATUS VARCHAR2(20) DEFAULT 'PENDING',  
	 CONSTRAINT ADOPTION_PROCESS_STATUS_CK CHECK ( 
            ADOPTION_STATUS IN
            ('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED')
        ), 
	 CONSTRAINT ADOPTION_PROCESS_DATES_CK CHECK ( 
            COMPLETION_DATE IS NULL
            OR COMPLETION_DATE >= APPLICATION_DATE
        ), 
	 CONSTRAINT ADOPTION_PROCESS_ID_PK PRIMARY KEY (ADOPTION_ID) 
, 
	 CONSTRAINT ADOPTION_PROCESS_ADOPTER_FK FOREIGN KEY (ADOPTER_ID) 
	  REFERENCES ADOPTER (ADOPTER_ID),  
	 CONSTRAINT ADOPTION_PROCESS_PET_FK FOREIGN KEY (PET_ID) 
	  REFERENCES PET (PET_ID),  
	 CONSTRAINT ADOPTION_PROCESS_EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_ID) 
	  REFERENCES EMPLOYEE (EMPLOYEE_ID)
   ) ;

-- ------------------------------------------------------------
-- SHELTER_ASSIGNMENT
-- ------------------------------------------------------------
CREATE TABLE SHELTER_ASSIGNMENT 
   (	PET_ID VARCHAR2(12),  
	SHELTER_ID VARCHAR2(12),  
	ASSIGN_DATE DATE NOT NULL,  
	RELEASE_DATE DATE,  
	 CONSTRAINT SHELTER_ASSIGNMENT_DATES_CK CHECK ( 
            RELEASE_DATE IS NULL
            OR RELEASE_DATE >= ASSIGN_DATE
        ), 
	 CONSTRAINT SHELTER_ASSIGNMENT_PK PRIMARY KEY (PET_ID, SHELTER_ID, ASSIGN_DATE) 
, 
	 CONSTRAINT SHELTER_ASSIGNMENT_PET_FK FOREIGN KEY (PET_ID) 
	  REFERENCES PET (PET_ID),  
	 CONSTRAINT SHELTER_ASSIGNMENT_SHELTER_FK FOREIGN KEY (SHELTER_ID) 
	  REFERENCES SHELTER (SHELTER_ID)
   ) ;

-- ------------------------------------------------------------
-- GIVES
-- ------------------------------------------------------------
CREATE TABLE GIVES 
   (	OWNER_ID VARCHAR2(12) NOT NULL,  
	DONOR_ID VARCHAR2(12) NOT NULL,  
	INCOME_ID VARCHAR2(12) NOT NULL,  
	 CONSTRAINT GIVES_PK PRIMARY KEY (OWNER_ID, DONOR_ID, INCOME_ID) 
, 
	 CONSTRAINT GIVES_OWNER_FK FOREIGN KEY (OWNER_ID) 
	  REFERENCES OWNER (OWNER_ID),  
	 CONSTRAINT GIVES_DONOR_FK FOREIGN KEY (DONOR_ID) 
	  REFERENCES DONOR (DONOR_ID),  
	 CONSTRAINT GIVES_INCOME_FK FOREIGN KEY (INCOME_ID) 
	  REFERENCES INCOME (INCOME_ID)
   ) ;

-- ------------------------------------------------------------
-- SALARY
-- ------------------------------------------------------------
CREATE TABLE SALARY 
   (	SALARY_ID VARCHAR2(12),  
	EMPLOYEE_ID VARCHAR2(12),  
	SUPERVISOR_ID VARCHAR2(12),  
	DOCTOR_ID VARCHAR2(12),  
	EXPENSE_ID VARCHAR2(12) NOT NULL,  
	SALARY_DATE DATE NOT NULL,  
	SALARY_AMOUNT NUMBER(12,2) NOT NULL,  
	SALARY_STATUS VARCHAR2(20) DEFAULT 'PAID',  
	 CONSTRAINT SALARY_AMOUNT_CK CHECK (SALARY_AMOUNT > 0),  
	 CONSTRAINT SALARY_STATUS_CK CHECK ( 
            SALARY_STATUS IN ('PENDING', 'PAID', 'CANCELLED')
        ), 
	 CONSTRAINT SALARY_SALARY_ID_PK PRIMARY KEY (SALARY_ID) 
, 
	 CONSTRAINT SALARY_PERSON_CK CHECK ( 
    EMPLOYEE_ID IS NOT NULL
    OR SUPERVISOR_ID IS NOT NULL
    OR DOCTOR_ID IS NOT NULL
), 
	 CONSTRAINT SALARY_EMPLOYEE_ID_FK FOREIGN KEY (EMPLOYEE_ID) 
	  REFERENCES EMPLOYEE (EMPLOYEE_ID),  
	 CONSTRAINT SALARY_SUPERVISOR_ID_FK FOREIGN KEY (SUPERVISOR_ID) 
	  REFERENCES SUPERVISOR (SUPERVISOR_ID),  
	 CONSTRAINT SALARY_DOCTOR_ID_FK FOREIGN KEY (DOCTOR_ID) 
	  REFERENCES DOCTOR (DOCTOR_ID),  
	 CONSTRAINT SALARY_EXPENSE_ID_FK FOREIGN KEY (EXPENSE_ID) 
	  REFERENCES EXPENSE (EXPENSE_ID)
   ) ;

COMMIT;