-- Simple view: persons and their derived age.
CREATE OR REPLACE VIEW VW_PERSON_BASIC AS
SELECT PERSON_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,GENDER,EMAIL,
       TRUNC(MONTHS_BETWEEN(SYSDATE,DATE_OF_BIRTH)/12) AGE
FROM PERSON;

-- Complex view: subtype/role membership.
CREATE OR REPLACE VIEW VW_PERSON_ROLES AS
SELECT p.PERSON_ID,p.FIRST_NAME,p.LAST_NAME,p.DATE_OF_BIRTH,p.GENDER,p.EMAIL,
       TRUNC(MONTHS_BETWEEN(SYSDATE,p.DATE_OF_BIRTH)/12) AGE,
       RTRIM(
         CASE WHEN d.PERSON_ID IS NOT NULL THEN 'DOCTOR,' END||
         CASE WHEN v.PERSON_ID IS NOT NULL THEN 'VOLUNTEER,' END||
         CASE WHEN s.PERSON_ID IS NOT NULL THEN 'SUPERVISOR,' END||
         CASE WHEN e.PERSON_ID IS NOT NULL THEN 'EMPLOYEE,' END||
         CASE WHEN a.PERSON_ID IS NOT NULL THEN 'ADOPTER,' END||
         CASE WHEN o.PERSON_ID IS NOT NULL THEN 'OWNER,' END||
         CASE WHEN dn.PERSON_ID IS NOT NULL THEN 'DONOR,' END,',') ROLES
FROM PERSON p
LEFT JOIN DOCTOR d ON d.PERSON_ID=p.PERSON_ID
LEFT JOIN VOLUNTEER v ON v.PERSON_ID=p.PERSON_ID
LEFT JOIN SUPERVISOR s ON s.PERSON_ID=p.PERSON_ID
LEFT JOIN EMPLOYEE e ON e.PERSON_ID=p.PERSON_ID
LEFT JOIN ADOPTER a ON a.PERSON_ID=p.PERSON_ID
LEFT JOIN OWNER o ON o.PERSON_ID=p.PERSON_ID
LEFT JOIN DONOR dn ON dn.PERSON_ID=p.PERSON_ID;

CREATE OR REPLACE VIEW VW_ROLE_DIRECTORY AS
SELECT 'DOCTOR' ROLE_NAME,p.PERSON_ID,p.FIRST_NAME||' '||p.LAST_NAME FULL_NAME,d.SPECIALIZATION DETAILS,d.SALARY AMOUNT FROM DOCTOR d JOIN PERSON p ON p.PERSON_ID=d.PERSON_ID
UNION ALL
SELECT 'VOLUNTEER',p.PERSON_ID,p.FIRST_NAME||' '||p.LAST_NAME,v.SKILL,NULL FROM VOLUNTEER v JOIN PERSON p ON p.PERSON_ID=v.PERSON_ID
UNION ALL
SELECT 'SUPERVISOR',p.PERSON_ID,p.FIRST_NAME||' '||p.LAST_NAME,'Shelter and adoption supervision',NULL FROM SUPERVISOR s JOIN PERSON p ON p.PERSON_ID=s.PERSON_ID
UNION ALL
SELECT 'EMPLOYEE',p.PERSON_ID,p.FIRST_NAME||' '||p.LAST_NAME,e.POSITION,e.SALARY FROM EMPLOYEE e JOIN PERSON p ON p.PERSON_ID=e.PERSON_ID
UNION ALL
SELECT 'ADOPTER',p.PERSON_ID,p.FIRST_NAME||' '||p.LAST_NAME,a.OCCUPATION,NULL FROM ADOPTER a JOIN PERSON p ON p.PERSON_ID=a.PERSON_ID
UNION ALL
SELECT 'DONOR',p.PERSON_ID,p.FIRST_NAME||' '||p.LAST_NAME,d.OCCUPATION,d.DONATION_AMOUNT FROM DONOR d JOIN PERSON p ON p.PERSON_ID=d.PERSON_ID
UNION ALL
SELECT 'OWNER',p.PERSON_ID,p.FIRST_NAME||' '||p.LAST_NAME,o.OCCUPATION,NULL FROM OWNER o JOIN PERSON p ON p.PERSON_ID=o.PERSON_ID;

CREATE OR REPLACE VIEW VW_PET_DETAILS AS
SELECT p.PET_ID,p.NAME,p.SPECIES,p.BREED,p.DOB,
       TRUNC(MONTHS_BETWEEN(SYSDATE,p.DOB)/12) AGE,p.WEIGHT,
       CASE WHEN l.PET_ID IS NOT NULL THEN 'LOCAL' WHEN g.PET_ID IS NOT NULL THEN 'GUEST' END PET_TYPE,
       l.ADOPTION_STATUS,l.IN_TAKE_DATE,g.CHECK_IN_DATE,g.RELEVANT_TIME
FROM PET p
LEFT JOIN LOCAL_PET l ON l.PET_ID=p.PET_ID
LEFT JOIN GUEST_PET g ON g.PET_ID=p.PET_ID;

CREATE OR REPLACE VIEW VW_SHELTER_OVERVIEW AS
SELECT s.SHELTER_ID,s.ROOM_TYPE,
       NVL(p.PET_COUNT,0) PET_COUNT,
       NVL(r.RESCUE_COUNT,0) RESCUE_COUNT,
       sup.SUPERVISOR_NAME
FROM SHELTER s
LEFT JOIN (SELECT SHELTER_ID,COUNT(*) PET_COUNT FROM PET_SHELTER GROUP BY SHELTER_ID) p ON p.SHELTER_ID=s.SHELTER_ID
LEFT JOIN (SELECT SHELTER_ID,COUNT(*) RESCUE_COUNT FROM RESCUE_SHELTER GROUP BY SHELTER_ID) r ON r.SHELTER_ID=s.SHELTER_ID
LEFT JOIN (
  SELECT ss.SHELTER_ID,pe.FIRST_NAME||' '||pe.LAST_NAME SUPERVISOR_NAME
  FROM SHELTER_SUPERVISION ss JOIN PERSON pe ON pe.PERSON_ID=ss.SUPERVISOR_ID
) sup ON sup.SHELTER_ID=s.SHELTER_ID;

CREATE OR REPLACE VIEW VW_RESCUE_DETAILS AS
SELECT r.RESCUE_ID,r.RESCUE_DATE,r.LOCATION,rs.SHELTER_ID,
       v.VOLUNTEER_ID,p.FIRST_NAME||' '||p.LAST_NAME VOLUNTEER_NAME
FROM RESCUE r
LEFT JOIN RESCUE_SHELTER rs ON rs.RESCUE_ID=r.RESCUE_ID
LEFT JOIN VOLUNTEER_RESCUE v ON v.RESCUE_ID=r.RESCUE_ID
LEFT JOIN PERSON p ON p.PERSON_ID=v.VOLUNTEER_ID;

CREATE OR REPLACE VIEW VW_ADOPTION_APPLICATIONS AS
SELECT ap.ADOPTION_ID,ap.APPLY_DATE,ap.STATUS,
       ap.ADOPTER_ID,ad.FIRST_NAME||' '||ad.LAST_NAME ADOPTER_NAME,
       ap.EMPLOYEE_ID,em.FIRST_NAME||' '||em.LAST_NAME EMPLOYEE_NAME,
       ap.LOCAL_PET_ID,pet.NAME PET_NAME,
       am.SUPERVISOR_ID,su.FIRST_NAME||' '||su.LAST_NAME SUPERVISOR_NAME,
       am.ASSIGN_DATE REVIEW_DATE
FROM ADOPTION_PROCESS ap
JOIN PERSON ad ON ad.PERSON_ID=ap.ADOPTER_ID
LEFT JOIN PERSON em ON em.PERSON_ID=ap.EMPLOYEE_ID
JOIN PET pet ON pet.PET_ID=ap.LOCAL_PET_ID
LEFT JOIN ADOPTION_MANAGEMENT am ON am.ADOPTION_ID=ap.ADOPTION_ID
LEFT JOIN PERSON su ON su.PERSON_ID=am.SUPERVISOR_ID;

CREATE OR REPLACE VIEW VW_MEDICAL_DETAILS AS
SELECT mr.RECORD_ID,mr.PET_ID,p.NAME PET_NAME,mr.HEALTH_STATUS,mr.DIAGNOSIS,mr.TREATMENT,
       m.MEDICINE_ID,m.DOSAGE,m.PRICE MEDICINE_PRICE,
       v.VACCINE_ID,v.VACCINE_NAME,v.V_DATE,v.NEXT_DOSE,v.PRICE VACCINE_PRICE
FROM MEDICAL_RECORD mr
JOIN PET p ON p.PET_ID=mr.PET_ID
LEFT JOIN MEDICAL_RECORD_MEDICINE mrm ON mrm.RECORD_ID=mr.RECORD_ID
LEFT JOIN MEDICINE m ON m.MEDICINE_ID=mrm.MEDICINE_ID
LEFT JOIN MEDICAL_RECORD_VACCINATION mrv ON mrv.RECORD_ID=mr.RECORD_ID
LEFT JOIN VACCINATION v ON v.VACCINE_ID=mrv.VACCINE_ID;

CREATE OR REPLACE VIEW VW_FINANCE_SUMMARY AS
SELECT f.FINANCE_ID,f.CURRENT_BALANCE,
       NVL(i.TOTAL_INCOME,0) TOTAL_INCOME,
       NVL(e.TOTAL_EXPENSES,0) TOTAL_EXPENSES,
       NVL(i.TOTAL_INCOME,0)-NVL(e.TOTAL_EXPENSES,0) NET_AMOUNT
FROM FINANCE f
LEFT JOIN (
  SELECT fi.FINANCE_ID,SUM(i.AMOUNT) TOTAL_INCOME
  FROM FINANCE_INCOME fi JOIN INCOME i ON i.SOURCE_ID=fi.SOURCE_ID
  GROUP BY fi.FINANCE_ID
) i ON i.FINANCE_ID=f.FINANCE_ID
LEFT JOIN (
  SELECT fe.FINANCE_ID,SUM(e.AMOUNT) TOTAL_EXPENSES
  FROM FINANCE_EXPENSE fe JOIN EXPENSES e ON e.SOURCE_ID=fe.SOURCE_ID
  GROUP BY fe.FINANCE_ID
) e ON e.FINANCE_ID=f.FINANCE_ID;

CREATE OR REPLACE VIEW VW_SALARY_DETAILS AS
SELECT s.SALARY_ID,s.RECORDED_BY_SUPERVISOR_ID,
       sp.FIRST_NAME||' '||sp.LAST_NAME RECORDED_BY,
       s.PAYEE_ID,pp.FIRST_NAME||' '||pp.LAST_NAME PAYEE_NAME,s.PAYEE_ROLE,
       s.SALARY_MONTH,TO_CHAR(s.PAYMENT_DATE,'YYYY-MM-DD') PAYMENT_DATE,
       s.EXPENSE_SOURCE_ID,x.SOURCE_NAME,s.SALARY_AMOUNT
FROM SALARY s
JOIN PERSON sp ON sp.PERSON_ID=s.RECORDED_BY_SUPERVISOR_ID
JOIN PERSON pp ON pp.PERSON_ID=s.PAYEE_ID
JOIN EXPENSES x ON x.SOURCE_ID=s.EXPENSE_SOURCE_ID;

CREATE OR REPLACE VIEW VW_DASHBOARD_STATS AS
SELECT (SELECT COUNT(*) FROM PERSON) PERSON_COUNT,
       (SELECT COUNT(*) FROM PET) PET_COUNT,
       (SELECT COUNT(*) FROM LOCAL_PET WHERE ADOPTION_STATUS='AVAILABLE') AVAILABLE_LOCAL_PETS,
       (SELECT COUNT(*) FROM ADOPTION_PROCESS WHERE STATUS='PENDING') PENDING_APPLICATIONS,
       (SELECT COUNT(*) FROM RESCUE) RESCUE_COUNT,
       (SELECT NVL(SUM(AMOUNT),0) FROM INCOME) TOTAL_INCOME,
       (SELECT NVL(SUM(AMOUNT),0) FROM EXPENSES) TOTAL_EXPENSES
FROM DUAL;
