-- Run ONLY after runtime testing succeeds.
ALTER TABLE PERSON DROP COLUMN NAME;
ALTER TABLE PERSON DROP COLUMN PHONE_NO;
ALTER TABLE PERSON DROP COLUMN CONTACT_NO;
COMMIT;

DESC PERSON;
DESC PERSON_PHONE;

SELECT
    p.PERSON_ID,
    p.FIRST_NAME,
    p.LAST_NAME,
    p.GENDER,
    p.DATE_OF_BIRTH,
    pp.PHONE_NO
FROM PERSON p
LEFT JOIN PERSON_PHONE pp
    ON pp.PERSON_ID = p.PERSON_ID
ORDER BY p.PERSON_ID, pp.PHONE_NO;