-- 1. Selection and projection
SELECT PERSON_ID,FIRST_NAME,LAST_NAME FROM PERSON;

-- 2. Relational and logical operators
SELECT * FROM EMPLOYEE WHERE SALARY >= 50000 AND POSITION IS NOT NULL;

-- 3. BETWEEN
SELECT * FROM RESCUE WHERE RESCUE_DATE BETWEEN TO_DATE('2026-01-01','YYYY-MM-DD') AND TO_DATE('2026-12-31','YYYY-MM-DD');

-- 4. IN / NOT IN
SELECT * FROM PET WHERE SPECIES IN ('Cat','Dog');
SELECT * FROM LOCAL_PET WHERE ADOPTION_STATUS NOT IN ('ADOPTED','ON_HOLD');

-- 5. LIKE / NOT LIKE
SELECT * FROM PERSON WHERE UPPER(FIRST_NAME) LIKE 'M%';
SELECT * FROM PERSON_ADDRESS WHERE UPPER(CITY) NOT LIKE 'D%';

-- 6. NULL / NOT NULL
SELECT * FROM PERSON WHERE EMAIL IS NOT NULL;

-- 7. ORDER BY
SELECT * FROM PET ORDER BY SPECIES ASC,NAME ASC;

-- 8. DISTINCT
SELECT DISTINCT SPECIES FROM PET;

-- 9. Concatenation and column alias
SELECT PERSON_ID,FIRST_NAME||' '||LAST_NAME AS FULL_NAME FROM PERSON;

-- 10. UPDATE, DELETE and COMMIT examples are demonstrated through frontend forms.
-- Use COMMIT after a successful data modification and ROLLBACK after a failed transaction.
