-- SINGLE-ROW FUNCTIONS
SELECT PERSON_ID,UPPER(FIRST_NAME) UPPER_NAME,LOWER(EMAIL) LOWER_EMAIL,
       INITCAP(CITY) CITY, LENGTH(FIRST_NAME) NAME_LENGTH
FROM PERSON JOIN PERSON_ADDRESS USING(PERSON_ID);

SELECT PET_ID,NAME,SUBSTR(NAME,1,3) SHORT_NAME,LPAD(PET_ID,8,'0') PADDED_ID,
       REPLACE(SPECIES,'Cat','Feline') DISPLAY_SPECIES
FROM PET;

SELECT MEDICINE_ID,PRICE,ROUND(PRICE/3,2) ROUND_VALUE,TRUNC(PRICE/3,2) TRUNC_VALUE FROM MEDICINE;

SELECT PET_ID,NAME,ROUND(MONTHS_BETWEEN(SYSDATE,DOB),1) AGE_MONTHS,ADD_MONTHS(DOB,12) FIRST_BIRTHDAY
FROM PET;

-- GROUP FUNCTIONS, GROUP BY and HAVING
SELECT SPECIES,COUNT(*) PET_COUNT,ROUND(AVG(WEIGHT),2) AVG_WEIGHT,MAX(WEIGHT) MAX_WEIGHT,MIN(WEIGHT) MIN_WEIGHT
FROM PET GROUP BY SPECIES HAVING COUNT(*) >= 1 ORDER BY SPECIES;

-- CROSS JOIN (limited for readable output)
SELECT p.NAME PET_NAME,s.ROOM_TYPE FROM PET p CROSS JOIN SHELTER s WHERE ROWNUM <= 10;

-- EQUIJOIN / INNER JOIN / JOIN ON
SELECT p.NAME,ps.SHELTER_ID FROM PET p JOIN PET_SHELTER ps ON ps.PET_ID=p.PET_ID;

-- NATURAL JOIN and JOIN USING
SELECT PET_ID,NAME,ADOPTION_STATUS FROM PET NATURAL JOIN LOCAL_PET;
SELECT PERSON_ID,FIRST_NAME,PHONE FROM PERSON JOIN PERSON_PHONE USING(PERSON_ID);

-- JOINING MORE THAN TWO TABLES
SELECT p.NAME,ps.SHELTER_ID,s.ROOM_TYPE FROM PET p JOIN PET_SHELTER ps ON ps.PET_ID=p.PET_ID JOIN SHELTER s ON s.SHELTER_ID=ps.SHELTER_ID;

-- NON-EQUALITY JOIN
SELECT p.NAME,p.WEIGHT,m.MEDICINE_ID,m.PRICE FROM PET p JOIN MEDICINE m ON m.PRICE > p.WEIGHT*10;

-- LEFT OUTER JOIN
SELECT p.PERSON_ID,p.FIRST_NAME,u.USERNAME FROM PERSON p LEFT OUTER JOIN SYSTEM_USER u ON u.PERSON_ID=p.PERSON_ID;

-- SELF JOIN: senior and junior doctors
SELECT senior.FIRST_NAME SENIOR_DOCTOR,junior.FIRST_NAME JUNIOR_DOCTOR
FROM DOCTOR_TRAINING t JOIN PERSON senior ON senior.PERSON_ID=t.SENIOR_DOCTOR_ID JOIN PERSON junior ON junior.PERSON_ID=t.JUNIOR_DOCTOR_ID;

-- SINGLE-ROW SUBQUERY
SELECT PERSON_ID,FIRST_NAME,LAST_NAME FROM PERSON
WHERE PERSON_ID=(SELECT PERSON_ID FROM EMPLOYEE WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEE));

-- MULTIPLE-ROW SUBQUERY with IN
SELECT PERSON_ID,FIRST_NAME,LAST_NAME FROM PERSON WHERE PERSON_ID IN (SELECT PERSON_ID FROM ADOPTER);

-- ANY and ALL
SELECT * FROM EMPLOYEE WHERE SALARY > ANY (SELECT SALARY FROM DOCTOR WHERE SALARY IS NOT NULL);
SELECT * FROM EMPLOYEE WHERE SALARY < ALL (SELECT SALARY FROM DOCTOR WHERE SALARY IS NOT NULL);

-- EXISTS and NOT EXISTS
SELECT p.PERSON_ID,p.FIRST_NAME FROM PERSON p WHERE EXISTS (SELECT 1 FROM SYSTEM_USER u WHERE u.PERSON_ID=p.PERSON_ID);
SELECT p.PERSON_ID,p.FIRST_NAME FROM PERSON p WHERE NOT EXISTS (SELECT 1 FROM SYSTEM_USER u WHERE u.PERSON_ID=p.PERSON_ID);

-- CORRELATED SUBQUERY
SELECT p.PET_ID,p.NAME FROM PET p
WHERE (SELECT COUNT(*) FROM MEDICAL_RECORD m WHERE m.PET_ID=p.PET_ID) >= 1;

-- SUBQUERY in HAVING
SELECT SPECIES,AVG(WEIGHT) AVG_WEIGHT FROM PET GROUP BY SPECIES
HAVING AVG(WEIGHT) > (SELECT MIN(WEIGHT) FROM PET);

-- SET OPERATIONS
SELECT PERSON_ID FROM ADOPTER UNION SELECT PERSON_ID FROM DONOR;
SELECT PERSON_ID FROM DONOR INTERSECT SELECT PERSON_ID FROM OWNER;

-- COMMON TABLE EXPRESSION (WITH clause): employee adoption workload.
-- This same Oracle query is executed from PetCare Insights in the frontend.
WITH EMPLOYEE_CASES AS (
  SELECT e.PERSON_ID,
         p.FIRST_NAME||' '||p.LAST_NAME EMPLOYEE_NAME,
         COUNT(ap.ADOPTION_ID) ASSIGNED_CASES,
         SUM(CASE WHEN ap.STATUS='APPROVED' THEN 1 ELSE 0 END) ACTIVE_CASES,
         SUM(CASE WHEN ap.STATUS='ADOPTED' THEN 1 ELSE 0 END) ADOPTED_CASES
  FROM EMPLOYEE e
  JOIN PERSON p ON p.PERSON_ID=e.PERSON_ID
  LEFT JOIN ADOPTION_PROCESS ap ON ap.EMPLOYEE_ID=e.PERSON_ID
  GROUP BY e.PERSON_ID,p.FIRST_NAME,p.LAST_NAME
), RANKED_CASES AS (
  SELECT ec.*,
         DENSE_RANK() OVER (ORDER BY ec.ASSIGNED_CASES DESC) WORKLOAD_RANK
  FROM EMPLOYEE_CASES ec
)
SELECT PERSON_ID,EMPLOYEE_NAME,ASSIGNED_CASES,ACTIVE_CASES,ADOPTED_CASES,WORKLOAD_RANK
FROM RANKED_CASES
ORDER BY WORKLOAD_RANK,EMPLOYEE_NAME;

-- VIEW queries
SELECT * FROM VW_PERSON_BASIC;
SELECT * FROM VW_ADOPTION_APPLICATIONS;
