CREATE OR REPLACE FUNCTION FN_PERSON_AGE(P_PERSON_ID VARCHAR2)
RETURN NUMBER
AS
  V_DOB PERSON.DATE_OF_BIRTH%TYPE;
BEGIN
  SELECT DATE_OF_BIRTH INTO V_DOB FROM PERSON WHERE PERSON_ID=P_PERSON_ID;
  RETURN TRUNC(MONTHS_BETWEEN(SYSDATE,V_DOB)/12);
EXCEPTION
  WHEN NO_DATA_FOUND THEN RETURN NULL;
END;
/
<<<<<<< HEAD
F
=======

>>>>>>> d69b99fc92d668a555103a21fad44187994cefc0
CREATE OR REPLACE FUNCTION FN_AVAILABLE_PET_COUNT
RETURN NUMBER
AS
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM LOCAL_PET WHERE ADOPTION_STATUS='AVAILABLE';
  RETURN V_COUNT;
END;
/

CREATE OR REPLACE PROCEDURE PR_CREATE_PERSON(
  P_PERSON_ID VARCHAR2,P_FIRST_NAME VARCHAR2,P_LAST_NAME VARCHAR2,
  P_DOB DATE,P_GENDER VARCHAR2,P_EMAIL VARCHAR2
)
AS
BEGIN
  INSERT INTO PERSON(PERSON_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,GENDER,EMAIL)
  VALUES(P_PERSON_ID,P_FIRST_NAME,P_LAST_NAME,P_DOB,P_GENDER,P_EMAIL);
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20001,'Person ID or email already exists');
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

-- Role-correct workflow: adopter submits without an employee assignment.
CREATE OR REPLACE PROCEDURE PR_SUBMIT_ADOPTION(
  P_ADOPTER_ID VARCHAR2,
  P_LOCAL_PET_ID VARCHAR2,
  P_ADOPTION_ID OUT VARCHAR2
)
AS
  V_AVAILABLE NUMBER;
  V_DUPLICATE NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_AVAILABLE
  FROM LOCAL_PET
  WHERE PET_ID=P_LOCAL_PET_ID AND ADOPTION_STATUS='AVAILABLE';

  IF V_AVAILABLE=0 THEN
    RAISE_APPLICATION_ERROR(-20011,'This pet is not currently available for adoption');
  END IF;

  SELECT COUNT(*) INTO V_DUPLICATE
  FROM ADOPTION_PROCESS
  WHERE ADOPTER_ID=P_ADOPTER_ID
    AND LOCAL_PET_ID=P_LOCAL_PET_ID
    AND STATUS IN ('PENDING','APPROVED');

  IF V_DUPLICATE>0 THEN
    RAISE_APPLICATION_ERROR(-20012,'You already have an active application for this pet');
  END IF;

<<<<<<< HEAD
  -- Use a 12-character ID without relying on a separately created sequence.
  P_ADOPTION_ID:='AD'||SUBSTR(RAWTOHEX(SYS_GUID()),1,10);
=======
  P_ADOPTION_ID:='AD'||LPAD(TO_CHAR(ADOPTION_ID_SEQ.NEXTVAL),6,'0');
>>>>>>> d69b99fc92d668a555103a21fad44187994cefc0

  INSERT INTO ADOPTION_PROCESS(
    ADOPTION_ID,ADOPTER_ID,EMPLOYEE_ID,LOCAL_PET_ID,APPLY_DATE,STATUS
  ) VALUES(
    P_ADOPTION_ID,P_ADOPTER_ID,NULL,P_LOCAL_PET_ID,TRUNC(SYSDATE),'PENDING'
  );
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

-- Only a supervisor calls this procedure after backend role authorization.
CREATE OR REPLACE PROCEDURE PR_REVIEW_ADOPTION(
  P_ADOPTION_ID VARCHAR2,
  P_SUPERVISOR_ID VARCHAR2,
  P_DECISION VARCHAR2,
  P_EMPLOYEE_ID VARCHAR2 DEFAULT NULL
)
AS
  V_STATUS ADOPTION_PROCESS.STATUS%TYPE;
  V_PET_ID ADOPTION_PROCESS.LOCAL_PET_ID%TYPE;
  V_EMPLOYEE NUMBER;
BEGIN
  SELECT STATUS,LOCAL_PET_ID INTO V_STATUS,V_PET_ID
  FROM ADOPTION_PROCESS
  WHERE ADOPTION_ID=P_ADOPTION_ID
  FOR UPDATE;

  IF V_STATUS<>'PENDING' THEN
    RAISE_APPLICATION_ERROR(-20013,'Only a pending application can be reviewed');
  END IF;

  IF P_DECISION NOT IN ('APPROVED','REJECTED') THEN
    RAISE_APPLICATION_ERROR(-20014,'Decision must be APPROVED or REJECTED');
  END IF;

  IF P_DECISION='APPROVED' THEN
    IF P_EMPLOYEE_ID IS NULL THEN
      RAISE_APPLICATION_ERROR(-20015,'Assign an employee before approving');
    END IF;

    SELECT COUNT(*) INTO V_EMPLOYEE
    FROM EMPLOYEE e
    JOIN SYSTEM_USER u ON u.PERSON_ID=e.PERSON_ID
    WHERE e.PERSON_ID=P_EMPLOYEE_ID
      AND u.USER_ROLE='EMPLOYEE'
      AND u.USER_STATUS='ACTIVE';

    IF V_EMPLOYEE=0 THEN
      RAISE_APPLICATION_ERROR(-20016,'The selected employee does not have an active employee account');
    END IF;

    UPDATE ADOPTION_PROCESS
    SET STATUS='APPROVED',EMPLOYEE_ID=P_EMPLOYEE_ID
    WHERE ADOPTION_ID=P_ADOPTION_ID;

    UPDATE LOCAL_PET SET ADOPTION_STATUS='PENDING' WHERE PET_ID=V_PET_ID;
  ELSE
    UPDATE ADOPTION_PROCESS
    SET STATUS='REJECTED',EMPLOYEE_ID=NULL
    WHERE ADOPTION_ID=P_ADOPTION_ID;
  END IF;

  MERGE INTO ADOPTION_MANAGEMENT target
  USING (SELECT P_ADOPTION_ID ADOPTION_ID FROM DUAL) source
  ON (target.ADOPTION_ID=source.ADOPTION_ID)
  WHEN MATCHED THEN UPDATE SET
    target.SUPERVISOR_ID=P_SUPERVISOR_ID,
    target.ASSIGN_DATE=TRUNC(SYSDATE),
    target.SALARY=NULL
  WHEN NOT MATCHED THEN INSERT(
    SUPERVISOR_ID,ADOPTION_ID,ASSIGN_DATE,SALARY
  ) VALUES(
    P_SUPERVISOR_ID,P_ADOPTION_ID,TRUNC(SYSDATE),NULL
  );
  COMMIT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20017,'Adoption application was not found');
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

<<<<<<< HEAD
-- Only the assigned employee may finalize an approved adoption as ADOPTED.
CREATE OR REPLACE PROCEDURE PR_MARK_ADOPTED(
=======
-- Only the assigned employee may complete an approved adoption.
CREATE OR REPLACE PROCEDURE PR_COMPLETE_ADOPTION(
>>>>>>> d69b99fc92d668a555103a21fad44187994cefc0
  P_ADOPTION_ID VARCHAR2,
  P_EMPLOYEE_ID VARCHAR2
)
AS
  V_PET_ID ADOPTION_PROCESS.LOCAL_PET_ID%TYPE;
BEGIN
  SELECT LOCAL_PET_ID INTO V_PET_ID
  FROM ADOPTION_PROCESS
  WHERE ADOPTION_ID=P_ADOPTION_ID
    AND EMPLOYEE_ID=P_EMPLOYEE_ID
    AND STATUS='APPROVED'
  FOR UPDATE;

  UPDATE ADOPTION_PROCESS
<<<<<<< HEAD
  SET STATUS='ADOPTED'
=======
  SET STATUS='COMPLETED'
>>>>>>> d69b99fc92d668a555103a21fad44187994cefc0
  WHERE ADOPTION_ID=P_ADOPTION_ID;

  UPDATE LOCAL_PET
  SET ADOPTION_STATUS='ADOPTED'
  WHERE PET_ID=V_PET_ID;
  COMMIT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    ROLLBACK;
<<<<<<< HEAD
    RAISE_APPLICATION_ERROR(-20018,'Only the assigned employee can mark an approved application as adopted');
=======
    RAISE_APPLICATION_ERROR(-20018,'Only the assigned employee can complete an approved application');
>>>>>>> d69b99fc92d668a555103a21fad44187994cefc0
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

-- Explicit Cursor: counts all pets and available local pets.
CREATE OR REPLACE PROCEDURE PR_CURSOR_PET_SUMMARY(P_TOTAL OUT NUMBER,P_AVAILABLE OUT NUMBER)
AS
  CURSOR C_PETS IS
    SELECT p.PET_ID,l.ADOPTION_STATUS FROM PET p LEFT JOIN LOCAL_PET l ON l.PET_ID=p.PET_ID;
  V_PET C_PETS%ROWTYPE;
BEGIN
  P_TOTAL:=0;
  P_AVAILABLE:=0;
  OPEN C_PETS;
  LOOP
    FETCH C_PETS INTO V_PET;
    EXIT WHEN C_PETS%NOTFOUND;
    P_TOTAL:=P_TOTAL+1;
    IF V_PET.ADOPTION_STATUS='AVAILABLE' THEN P_AVAILABLE:=P_AVAILABLE+1; END IF;
  END LOOP;
  CLOSE C_PETS;
END;
/

-- %ROWTYPE record and named exception handling.
CREATE OR REPLACE PROCEDURE PR_FIND_PERSON(P_PERSON_ID VARCHAR2,P_FULL_NAME OUT VARCHAR2,P_MESSAGE OUT VARCHAR2)
AS
  V_PERSON PERSON%ROWTYPE;
BEGIN
  SELECT * INTO V_PERSON FROM PERSON WHERE PERSON_ID=P_PERSON_ID;
  P_FULL_NAME:=V_PERSON.FIRST_NAME||' '||V_PERSON.LAST_NAME;
  P_MESSAGE:='Person found';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    P_FULL_NAME:=NULL;
    P_MESSAGE:='NO_DATA_FOUND handled: person does not exist';
  WHEN TOO_MANY_ROWS THEN
    P_FULL_NAME:=NULL;
    P_MESSAGE:='TOO_MANY_ROWS handled';
  WHEN OTHERS THEN
    P_FULL_NAME:=NULL;
    P_MESSAGE:='Unexpected exception handled';
END;
/
<<<<<<< HEAD

-- Owner directory lookup with explicit NO_DATA_FOUND handling for empty results.
CREATE OR REPLACE PROCEDURE PR_OWNER_DIRECTORY(
  P_SEARCH VARCHAR2,
  P_MESSAGE OUT VARCHAR2,
  P_ROWS OUT SYS_REFCURSOR
)
AS
  V_MATCH_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_MATCH_COUNT
  FROM OWNER o JOIN PERSON p ON p.PERSON_ID=o.PERSON_ID
  WHERE P_SEARCH IS NULL
     OR UPPER(o.PERSON_ID)=UPPER(P_SEARCH)
     OR UPPER(TRIM(p.FIRST_NAME||' '||p.LAST_NAME))=UPPER(P_SEARCH)
     OR UPPER(p.FIRST_NAME)=UPPER(P_SEARCH)
     OR UPPER(p.LAST_NAME)=UPPER(P_SEARCH)
     OR EXISTS (
       SELECT 1 FROM PERSON_PHONE pp
       WHERE pp.PERSON_ID=o.PERSON_ID AND pp.PHONE=P_SEARCH
     );

  IF V_MATCH_COUNT=0 THEN
    RAISE NO_DATA_FOUND;
  END IF;

  P_MESSAGE:='Owner records found';
  OPEN P_ROWS FOR
    SELECT o.PERSON_ID OWNER_ID,p.FIRST_NAME||' '||p.LAST_NAME OWNER_NAME,
      o.OCCUPATION,(SELECT MIN(pp.PHONE) FROM PERSON_PHONE pp WHERE pp.PERSON_ID=o.PERSON_ID) PHONE,
      pet.PET_ID,pet.NAME PET_NAME,pet.SPECIES,pet.BREED,
      TO_CHAR(gp.CHECK_IN_DATE,'YYYY-MM-DD') CHECK_IN_DATE,gp.RELEVANT_TIME
    FROM OWNER o JOIN PERSON p ON p.PERSON_ID=o.PERSON_ID
    LEFT JOIN GUEST_PET_OWNER gpo ON gpo.OWNER_ID=o.PERSON_ID
    LEFT JOIN GUEST_PET gp ON gp.PET_ID=gpo.PET_ID
    LEFT JOIN PET pet ON pet.PET_ID=gp.PET_ID
    WHERE P_SEARCH IS NULL
       OR UPPER(o.PERSON_ID)=UPPER(P_SEARCH)
       OR UPPER(TRIM(p.FIRST_NAME||' '||p.LAST_NAME))=UPPER(P_SEARCH)
       OR UPPER(p.FIRST_NAME)=UPPER(P_SEARCH)
       OR UPPER(p.LAST_NAME)=UPPER(P_SEARCH)
       OR EXISTS (
         SELECT 1 FROM PERSON_PHONE pp
         WHERE pp.PERSON_ID=o.PERSON_ID AND pp.PHONE=P_SEARCH
       )
    ORDER BY p.FIRST_NAME,p.LAST_NAME,pet.NAME;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    P_MESSAGE:='No records available';
    OPEN P_ROWS FOR
      SELECT CAST(NULL AS VARCHAR2(12)) OWNER_ID,
             CAST(NULL AS VARCHAR2(121)) OWNER_NAME,
             CAST(NULL AS VARCHAR2(100)) PHONE,
             CAST(NULL AS VARCHAR2(100)) OCCUPATION,
             CAST(NULL AS VARCHAR2(12)) PET_ID,
             CAST(NULL AS VARCHAR2(50)) PET_NAME,
             CAST(NULL AS VARCHAR2(30)) SPECIES,
             CAST(NULL AS VARCHAR2(30)) BREED,
             CAST(NULL AS VARCHAR2(10)) CHECK_IN_DATE,
             CAST(NULL AS VARCHAR2(100)) RELEVANT_TIME
      FROM DUAL
      WHERE 1=0;
  WHEN OTHERS THEN
    P_MESSAGE:='Unexpected exception handled while loading owner records';
    OPEN P_ROWS FOR
      SELECT CAST(NULL AS VARCHAR2(12)) OWNER_ID,
             CAST(NULL AS VARCHAR2(121)) OWNER_NAME,
             CAST(NULL AS VARCHAR2(100)) PHONE,
             CAST(NULL AS VARCHAR2(100)) OCCUPATION,
             CAST(NULL AS VARCHAR2(12)) PET_ID,
             CAST(NULL AS VARCHAR2(50)) PET_NAME,
             CAST(NULL AS VARCHAR2(30)) SPECIES,
             CAST(NULL AS VARCHAR2(30)) BREED,
             CAST(NULL AS VARCHAR2(10)) CHECK_IN_DATE,
             CAST(NULL AS VARCHAR2(100)) RELEVANT_TIME
      FROM DUAL
      WHERE 1=0;
END;
/
=======
>>>>>>> d69b99fc92d668a555103a21fad44187994cefc0
