-- Pet Adoption role upgrade (reference/audit copy)
-- Applied automatically by backend/applyRoleUpgrade.js.

-- Final ER compatibility expected by the new routes:
-- VOLUNTEER.SKILLS
-- EMPLOYEE/SUPERVISOR/DOCTOR.SALARY
-- VACCINATION.VACCINE_PRICE
-- MEDICINE.PRICE
-- MEDICAL_RECORD.HEALTH_STATUS
-- EXPENSE.SOURCE_NAME

CREATE OR REPLACE VIEW V_SUPERVISOR_PERSON_INFO AS
SELECT p.PERSON_ID,
       p.FIRST_NAME,
       p.LAST_NAME,
       TRIM(p.FIRST_NAME || ' ' || p.LAST_NAME) AS FULL_NAME,
       (SELECT LISTAGG(pp.PHONE_NO, ', ') WITHIN GROUP (ORDER BY pp.PHONE_NO)
          FROM PERSON_PHONE pp
         WHERE pp.PERSON_ID = p.PERSON_ID) AS PHONE_NO,
       p.EMAIL,
       p.ADDRESS,
       p.DATE_OF_BIRTH,
       p.GENDER,
       CASE WHEN p.DATE_OF_BIRTH IS NULL THEN NULL
            ELSE TRUNC(MONTHS_BETWEEN(SYSDATE, p.DATE_OF_BIRTH) / 12) END AS AGE
FROM PERSON p;

CREATE OR REPLACE VIEW V_SUPERVISOR_STAFF_INFO AS
SELECT p.PERSON_ID,
       TRIM(p.FIRST_NAME || ' ' || p.LAST_NAME) AS FULL_NAME,
       (SELECT LISTAGG(pp.PHONE_NO, ', ') WITHIN GROUP (ORDER BY pp.PHONE_NO)
          FROM PERSON_PHONE pp
         WHERE pp.PERSON_ID = p.PERSON_ID) AS PHONE_NO,
       p.EMAIL,
       CASE WHEN s.SUPERVISOR_ID IS NOT NULL THEN 'SUPERVISOR'
            WHEN d.DOCTOR_ID IS NOT NULL THEN 'DOCTOR'
            WHEN e.EMPLOYEE_ID IS NOT NULL THEN 'EMPLOYEE'
            WHEN v.VOLUNTEER_ID IS NOT NULL THEN 'VOLUNTEER' END AS STAFF_ROLE,
       e.HIRE_DATE,
       e.JOB_TITLE,
       e.EMPLOYMENT_STATUS,
       s.ASSIGNED_DATE,
       d.LICENSE_NO,
       d.SPECIALIZATION,
       v.JOIN_DATE,
       v.AVAILABILITY,
       v.SKILLS,
       CASE WHEN s.SUPERVISOR_ID IS NOT NULL THEN s.SALARY
            WHEN d.DOCTOR_ID IS NOT NULL THEN d.SALARY
            ELSE e.SALARY END AS CURRENT_SALARY
FROM PERSON p
LEFT JOIN EMPLOYEE e ON e.EMPLOYEE_ID = p.PERSON_ID
LEFT JOIN SUPERVISOR s ON s.SUPERVISOR_ID = p.PERSON_ID
LEFT JOIN DOCTOR d ON d.DOCTOR_ID = p.PERSON_ID
LEFT JOIN VOLUNTEER v ON v.VOLUNTEER_ID = p.PERSON_ID
WHERE e.EMPLOYEE_ID IS NOT NULL
   OR s.SUPERVISOR_ID IS NOT NULL
   OR d.DOCTOR_ID IS NOT NULL
   OR v.VOLUNTEER_ID IS NOT NULL;

CREATE OR REPLACE VIEW V_SUPERVISOR_SALARY_HISTORY AS
SELECT sa.SALARY_ID,
       CASE WHEN sa.EMPLOYEE_ID IS NOT NULL THEN 'EMPLOYEE'
            WHEN sa.SUPERVISOR_ID IS NOT NULL THEN 'SUPERVISOR'
            WHEN sa.DOCTOR_ID IS NOT NULL THEN 'DOCTOR' END AS RECEIVER_TYPE,
       NVL(sa.EMPLOYEE_ID, NVL(sa.SUPERVISOR_ID, sa.DOCTOR_ID)) AS RECEIVER_ID,
       TRIM(p.FIRST_NAME || ' ' || p.LAST_NAME) AS RECEIVER_NAME,
       sa.SALARY_DATE,
       sa.SALARY_AMOUNT,
       sa.SALARY_STATUS,
       sa.EXPENSE_ID,
       ex.SOURCE_NAME,
       ex.EXPENSE_DESCRIPTION,
       ex.EXPENSE_STATUS
FROM SALARY sa
JOIN PERSON p
  ON p.PERSON_ID = NVL(sa.EMPLOYEE_ID, NVL(sa.SUPERVISOR_ID, sa.DOCTOR_ID))
JOIN EXPENSE ex
  ON ex.EXPENSE_ID = sa.EXPENSE_ID;