-- Development-only accounts. Every hash below is bcrypt for the password: password
INSERT ALL
 INTO SYSTEM_USER VALUES ('U001','P001','admin','$2b$10$epynEfs4psB00OHzoxOiH.V9QkT5PaOlBozO1NBbo8UzYv4CZwQD.','ADMIN','ACTIVE')
 INTO SYSTEM_USER VALUES ('U002','P002','employee','$2b$10$XvuglmNy0ZDhJsIFklbgXOPFEEewtTXXNyKgstByzx0wg86mHrQm.','EMPLOYEE','ACTIVE')
 INTO SYSTEM_USER VALUES ('U003','P003','doctor','$2b$10$nTWTsY3VXS3r5WUQBUQnPOd/tyLq5qrYU9xFgMcqX9lRBi2K60ibu','DOCTOR','ACTIVE')
 INTO SYSTEM_USER VALUES ('U004','P013','supervisor','$2b$10$NEOcrB1nI0uapYfoHkkppukLrVSYIawwFtaY7KRf3vlIPuwmo/XTq','SUPERVISOR','ACTIVE')
 INTO SYSTEM_USER VALUES ('U005','P016','adopter','$2b$10$O3j/sb0rvbBQfChhT/tNbelHt/rRN6/1hNezXQHf8SQ0aPeQHaRzm','ADOPTER','ACTIVE')
 INTO SYSTEM_USER VALUES ('U006','P008','volunteer','$2b$10$epynEfs4psB00OHzoxOiH.V9QkT5PaOlBozO1NBbo8UzYv4CZwQD.','VOLUNTEER','ACTIVE')
SELECT 1 FROM DUAL;

INSERT ALL
 INTO SYSTEM_USER_ROLE(USER_ID,ROLE_NAME) VALUES ('U001','ADMIN')
 INTO SYSTEM_USER_ROLE(USER_ID,ROLE_NAME) VALUES ('U002','EMPLOYEE')
 INTO SYSTEM_USER_ROLE(USER_ID,ROLE_NAME) VALUES ('U003','DOCTOR')
 INTO SYSTEM_USER_ROLE(USER_ID,ROLE_NAME) VALUES ('U004','SUPERVISOR')
 INTO SYSTEM_USER_ROLE(USER_ID,ROLE_NAME) VALUES ('U005','ADOPTER')
 INTO SYSTEM_USER_ROLE(USER_ID,ROLE_NAME) VALUES ('U006','VOLUNTEER')
SELECT 1 FROM DUAL;

MERGE INTO SYSTEM_USER_ROLE target
USING (
  SELECT DISTINCT USER_ID,ROLE_NAME FROM (
    SELECT u.USER_ID,u.USER_ROLE ROLE_NAME FROM SYSTEM_USER u
    UNION ALL SELECT u.USER_ID,'SUPERVISOR' FROM SYSTEM_USER u JOIN SUPERVISOR r ON r.PERSON_ID=u.PERSON_ID
    UNION ALL SELECT u.USER_ID,'EMPLOYEE' FROM SYSTEM_USER u JOIN EMPLOYEE r ON r.PERSON_ID=u.PERSON_ID
    UNION ALL SELECT u.USER_ID,'DOCTOR' FROM SYSTEM_USER u JOIN DOCTOR r ON r.PERSON_ID=u.PERSON_ID
    UNION ALL SELECT u.USER_ID,'VOLUNTEER' FROM SYSTEM_USER u JOIN VOLUNTEER r ON r.PERSON_ID=u.PERSON_ID
    UNION ALL SELECT u.USER_ID,'ADOPTER' FROM SYSTEM_USER u JOIN ADOPTER r ON r.PERSON_ID=u.PERSON_ID
    UNION ALL SELECT u.USER_ID,'OWNER' FROM SYSTEM_USER u JOIN OWNER r ON r.PERSON_ID=u.PERSON_ID
    UNION ALL SELECT u.USER_ID,'DONOR' FROM SYSTEM_USER u JOIN DONOR r ON r.PERSON_ID=u.PERSON_ID
  )
) source
ON (target.USER_ID=source.USER_ID AND target.ROLE_NAME=source.ROLE_NAME)
WHEN NOT MATCHED THEN INSERT (USER_ID,ROLE_NAME) VALUES (source.USER_ID,source.ROLE_NAME);
COMMIT;
