SET SERVEROUTPUT ON

DECLARE
  V_TABLES NUMBER;
  V_ERRORS NUMBER;
  V_ORPHANS NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_TABLES FROM USER_TABLES WHERE TABLE_NAME IN (
<<<<<<< HEAD
    'PERSON','PERSON_ADDRESS','PERSON_PHONE','SYSTEM_USER','SYSTEM_USER_ROLE','ROLE_APPLICATION','EMERGENCY_NO','DOCTOR','VOLUNTEER','SUPERVISOR','ADOPTER','EMPLOYEE','DONOR','OWNER','DOCTOR_TRAINING','RESCUE','SHELTER','PET','LOCAL_PET','GUEST_PET','RESCUE_SHELTER','PET_SHELTER','GUEST_PET_OWNER','VOLUNTEER_RESCUE','MEDICAL_RECORD','MEDICINE','VACCINATION','MEDICAL_RECORD_MEDICINE','MEDICAL_RECORD_VACCINATION','FINANCE','INCOME','EXPENSES','FINANCE_INCOME','FINANCE_EXPENSE','DONATION','OWNER_MEDICINE','EXPENSE_MEDICINE','EXPENSE_VACCINATION','SHELTER_SUPERVISION','ADOPTION_PROCESS','ADOPTION_MANAGEMENT','SALARY','AUDIT_LOG'
=======
    'PERSON','PERSON_ADDRESS','PERSON_PHONE','SYSTEM_USER','EMERGENCY_NO','DOCTOR','VOLUNTEER','SUPERVISOR','ADOPTER','EMPLOYEE','DONOR','OWNER','DOCTOR_TRAINING','RESCUE','SHELTER','PET','LOCAL_PET','GUEST_PET','RESCUE_SHELTER','PET_SHELTER','GUEST_PET_OWNER','VOLUNTEER_RESCUE','MEDICAL_RECORD','MEDICINE','VACCINATION','MEDICAL_RECORD_MEDICINE','MEDICAL_RECORD_VACCINATION','FINANCE','INCOME','EXPENSES','FINANCE_INCOME','FINANCE_EXPENSE','DONATION','OWNER_MEDICINE','EXPENSE_MEDICINE','EXPENSE_VACCINATION','SHELTER_SUPERVISION','ADOPTION_PROCESS','ADOPTION_MANAGEMENT','SALARY'
>>>>>>> d69b99fc92d668a555103a21fad44187994cefc0
  );

  SELECT COUNT(*) INTO V_ERRORS FROM USER_ERRORS WHERE TYPE IN ('PROCEDURE','FUNCTION','VIEW','TYPE','TRIGGER');

  SELECT
    (SELECT COUNT(*) FROM PERSON_PHONE PP WHERE NOT EXISTS (SELECT 1 FROM PERSON P WHERE P.PERSON_ID=PP.PERSON_ID))+
    (SELECT COUNT(*) FROM ADOPTION_PROCESS A WHERE NOT EXISTS (SELECT 1 FROM LOCAL_PET L WHERE L.PET_ID=A.LOCAL_PET_ID))
  INTO V_ORPHANS FROM DUAL;

<<<<<<< HEAD
  DBMS_OUTPUT.PUT_LINE('EXPECTED TABLES FOUND: '||V_TABLES||'/43');
  DBMS_OUTPUT.PUT_LINE('COMPILATION ERRORS: '||V_ERRORS);
  DBMS_OUTPUT.PUT_LINE('ORPHAN ROWS: '||V_ORPHANS);

  IF V_TABLES=43 AND V_ERRORS=0 AND V_ORPHANS=0 THEN
=======
  DBMS_OUTPUT.PUT_LINE('EXPECTED TABLES FOUND: '||V_TABLES||'/40');
  DBMS_OUTPUT.PUT_LINE('COMPILATION ERRORS: '||V_ERRORS);
  DBMS_OUTPUT.PUT_LINE('ORPHAN ROWS: '||V_ORPHANS);

  IF V_TABLES=40 AND V_ERRORS=0 AND V_ORPHANS=0 THEN
>>>>>>> d69b99fc92d668a555103a21fad44187994cefc0
    DBMS_OUTPUT.PUT_LINE('VERIFICATION PASSED');
  ELSE
    DBMS_OUTPUT.PUT_LINE('VERIFICATION FAILED');
  END IF;
END;
/

SELECT 'PERSON' TABLE_NAME,COUNT(*) ROW_COUNT FROM PERSON
UNION ALL SELECT 'PET',COUNT(*) FROM PET
UNION ALL SELECT 'RESCUE',COUNT(*) FROM RESCUE
UNION ALL SELECT 'ADOPTION_PROCESS',COUNT(*) FROM ADOPTION_PROCESS
UNION ALL SELECT 'MEDICAL_RECORD',COUNT(*) FROM MEDICAL_RECORD
UNION ALL SELECT 'INCOME',COUNT(*) FROM INCOME
UNION ALL SELECT 'EXPENSES',COUNT(*) FROM EXPENSES;

SELECT * FROM VW_DASHBOARD_STATS;
SELECT FN_AVAILABLE_PET_COUNT AVAILABLE_PETS FROM DUAL;
