-- One-time migration for an existing PetCare database.
-- Open this file from the database folder in SQL Developer and run with F5.

ALTER TABLE ADOPTION_PROCESS MODIFY (EMPLOYEE_ID NULL);

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME='ADOPTION_ID_SEQ';

  IF V_COUNT=0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ADOPTION_ID_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT
  FROM USER_CONSTRAINTS
  WHERE TABLE_NAME='ADOPTION_MANAGEMENT'
    AND CONSTRAINT_NAME='UK_ADOPT_MGMT_ADOPTION';

  IF V_COUNT=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ADOPTION_MANAGEMENT ADD CONSTRAINT UK_ADOPT_MGMT_ADOPTION UNIQUE (ADOPTION_ID)';
  END IF;
END;
/

CREATE OR REPLACE VIEW VW_ADOPTION_APPLICATIONS AS
SELECT ap.ADOPTION_ID,ap.APPLY_DATE,ap.STATUS,
       ap.ADOPTER_ID,ad.FIRST_NAME||' '||ad.LAST_NAME ADOPTER_NAME,
       ap.EMPLOYEE_ID,em.FIRST_NAME||' '||em.LAST_NAME EMPLOYEE_NAME,
       ap.LOCAL_PET_ID,pet.NAME PET_NAME,
       am.SUPERVISOR_ID,su.FIRST_NAME||' '||su.LAST_NAME SUPERVISOR_NAME,
       am.ASSIGN_DATE REVIEW_DATE
FROM ADOPTION_PROCESS ap
JOIN PERSON ad ON ad.PERSON_ID=ap.ADOPTER_ID
LEFT JOIN PERSON em ON em.PERSON_ID=ap.EMPLOYEE_ID
JOIN PET pet ON pet.PET_ID=ap.LOCAL_PET_ID
LEFT JOIN ADOPTION_MANAGEMENT am ON am.ADOPTION_ID=ap.ADOPTION_ID
LEFT JOIN PERSON su ON su.PERSON_ID=am.SUPERVISOR_ID;

-- Normalize existing demo/history rows to the corrected responsibilities.
DELETE FROM ADOPTION_MANAGEMENT
WHERE ADOPTION_ID IN (SELECT ADOPTION_ID FROM ADOPTION_PROCESS WHERE STATUS='PENDING');

UPDATE ADOPTION_PROCESS
SET EMPLOYEE_ID=NULL
WHERE STATUS IN ('PENDING','REJECTED','CANCELLED');

UPDATE ADOPTION_PROCESS ap
SET EMPLOYEE_ID=(
  SELECT MIN(e.PERSON_ID)
  FROM EMPLOYEE e
  JOIN SYSTEM_USER u ON u.PERSON_ID=e.PERSON_ID
  WHERE u.USER_ROLE='EMPLOYEE' AND u.USER_STATUS='ACTIVE'
)
WHERE ap.STATUS='APPROVED'
  AND NOT EXISTS (
    SELECT 1 FROM SYSTEM_USER u
    WHERE u.PERSON_ID=ap.EMPLOYEE_ID
      AND u.USER_ROLE='EMPLOYEE'
      AND u.USER_STATUS='ACTIVE'
  );

UPDATE LOCAL_PET l
SET ADOPTION_STATUS=CASE
<<<<<<< HEAD
  WHEN EXISTS (SELECT 1 FROM ADOPTION_PROCESS a WHERE a.LOCAL_PET_ID=l.PET_ID AND a.STATUS='ADOPTED') THEN 'ADOPTED'
=======
  WHEN EXISTS (SELECT 1 FROM ADOPTION_PROCESS a WHERE a.LOCAL_PET_ID=l.PET_ID AND a.STATUS='COMPLETED') THEN 'ADOPTED'
>>>>>>> d69b99fc92d668a555103a21fad44187994cefc0
  WHEN EXISTS (SELECT 1 FROM ADOPTION_PROCESS a WHERE a.LOCAL_PET_ID=l.PET_ID AND a.STATUS='APPROVED') THEN 'PENDING'
  ELSE 'AVAILABLE'
END
WHERE EXISTS (SELECT 1 FROM ADOPTION_PROCESS a WHERE a.LOCAL_PET_ID=l.PET_ID);

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PR_PROCESS_ADOPTION';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Recompile all functions/procedures, including the new role-correct adoption workflow.
@@06_plsql.sql

COMMIT;

SELECT COLUMN_NAME,NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME='ADOPTION_PROCESS' AND COLUMN_NAME='EMPLOYEE_ID';

SELECT OBJECT_NAME,STATUS
FROM USER_OBJECTS
<<<<<<< HEAD
WHERE OBJECT_NAME IN ('VW_ADOPTION_APPLICATIONS','PR_SUBMIT_ADOPTION','PR_REVIEW_ADOPTION','PR_MARK_ADOPTED')
=======
WHERE OBJECT_NAME IN ('VW_ADOPTION_APPLICATIONS','PR_SUBMIT_ADOPTION','PR_REVIEW_ADOPTION','PR_COMPLETE_ADOPTION')
>>>>>>> d69b99fc92d668a555103a21fad44187994cefc0
ORDER BY OBJECT_NAME;

PROMPT ADOPTION WORKFLOW MIGRATION COMPLETED
