-- One-time migration for the corrected payroll model and owner directory.
-- Run this file once with F5 in SQL Developer on an existing PetCare schema.

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_SALARY_DETAILS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE!=-942 THEN RAISE; END IF;
END;
/

CREATE TABLE SALARY_NEW (
  SALARY_ID VARCHAR2(12) CONSTRAINT PK_SALARY_V2 PRIMARY KEY,
  RECORDED_BY_SUPERVISOR_ID VARCHAR2(12) NOT NULL,
  PAYEE_ID VARCHAR2(12) NOT NULL,
  PAYEE_ROLE VARCHAR2(20) NOT NULL,
  EXPENSE_SOURCE_ID VARCHAR2(12) NOT NULL,
  SALARY_MONTH VARCHAR2(7) NOT NULL,
  PAYMENT_DATE DATE NOT NULL,
  SALARY_AMOUNT NUMBER(12,2) NOT NULL,
  CONSTRAINT UK_SALARY_EXPENSE_V2 UNIQUE (EXPENSE_SOURCE_ID),
  CONSTRAINT FK_SALARY_RECORDED_BY_V2 FOREIGN KEY (RECORDED_BY_SUPERVISOR_ID) REFERENCES SUPERVISOR(PERSON_ID),
  CONSTRAINT FK_SALARY_PAYEE_V2 FOREIGN KEY (PAYEE_ID) REFERENCES PERSON(PERSON_ID),
  CONSTRAINT FK_SALARY_EXPENSE_V2 FOREIGN KEY (EXPENSE_SOURCE_ID) REFERENCES EXPENSES(SOURCE_ID),
  CONSTRAINT CK_SALARY_PAYEE_ROLE_V2 CHECK (PAYEE_ROLE IN ('SUPERVISOR','EMPLOYEE','DOCTOR')),
  CONSTRAINT CK_SALARY_AMOUNT_V2 CHECK (SALARY_AMOUNT >= 0)
);

-- The old design had one employee and one doctor in the same payment.
-- Preserve each old amount as one Employee payment because EMPLOYEE_ID was
-- the operational payee field used by the existing demo records.
INSERT INTO SALARY_NEW(
  SALARY_ID,RECORDED_BY_SUPERVISOR_ID,PAYEE_ID,PAYEE_ROLE,
  EXPENSE_SOURCE_ID,SALARY_MONTH,PAYMENT_DATE,SALARY_AMOUNT
)
SELECT 'SL'||LPAD(ROWNUM,8,'0'),SUPERVISOR_ID,EMPLOYEE_ID,'EMPLOYEE',
       EXPENSE_SOURCE_ID,TO_CHAR(ADD_MONTHS(DATE '2026-01-01',ROWNUM-1),'YYYY-MM'),
       LAST_DAY(ADD_MONTHS(DATE '2026-01-01',ROWNUM-1)),SALARY_AMOUNT
FROM SALARY;

DROP TABLE SALARY CASCADE CONSTRAINTS;
RENAME SALARY_NEW TO SALARY;

CREATE OR REPLACE TRIGGER TRG_SALARY_PAYEE_ROLE
BEFORE INSERT OR UPDATE OF PAYEE_ID,PAYEE_ROLE ON SALARY
FOR EACH ROW
DECLARE
  V_COUNT NUMBER;
BEGIN
  IF :NEW.PAYEE_ROLE='SUPERVISOR' THEN
    SELECT COUNT(*) INTO V_COUNT FROM SUPERVISOR WHERE PERSON_ID=:NEW.PAYEE_ID;
  ELSIF :NEW.PAYEE_ROLE='EMPLOYEE' THEN
    SELECT COUNT(*) INTO V_COUNT FROM EMPLOYEE WHERE PERSON_ID=:NEW.PAYEE_ID;
  ELSE
    SELECT COUNT(*) INTO V_COUNT FROM DOCTOR WHERE PERSON_ID=:NEW.PAYEE_ID;
  END IF;

  IF V_COUNT=0 THEN
    RAISE_APPLICATION_ERROR(-20031,'Selected person does not have the chosen payroll role');
  END IF;
END;
/

SHOW ERRORS TRIGGER TRG_SALARY_PAYEE_ROLE

CREATE OR REPLACE VIEW VW_SALARY_DETAILS AS
SELECT s.SALARY_ID,s.RECORDED_BY_SUPERVISOR_ID,
       sp.FIRST_NAME||' '||sp.LAST_NAME RECORDED_BY,
       s.PAYEE_ID,pp.FIRST_NAME||' '||pp.LAST_NAME PAYEE_NAME,s.PAYEE_ROLE,
       s.SALARY_MONTH,TO_CHAR(s.PAYMENT_DATE,'YYYY-MM-DD') PAYMENT_DATE,
       s.EXPENSE_SOURCE_ID,x.SOURCE_NAME,s.SALARY_AMOUNT
FROM SALARY s
JOIN PERSON sp ON sp.PERSON_ID=s.RECORDED_BY_SUPERVISOR_ID
JOIN PERSON pp ON pp.PERSON_ID=s.PAYEE_ID
JOIN EXPENSES x ON x.SOURCE_ID=s.EXPENSE_SOURCE_ID;

SELECT OBJECT_NAME,STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME IN ('SALARY','VW_SALARY_DETAILS','TRG_SALARY_PAYEE_ROLE')
ORDER BY OBJECT_NAME;

SELECT SALARY_ID,PAYEE_NAME,PAYEE_ROLE,SALARY_MONTH,SALARY_AMOUNT,RECORDED_BY
FROM VW_SALARY_DETAILS
ORDER BY PAYMENT_DATE;

COMMIT;

PROMPT PAYROLL AND OWNER DIRECTORY MIGRATION COMPLETED
