-- Run once with F5 on an existing database. No existing role or account is deleted.
SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SYSTEM_USER_ROLE (
      USER_ID VARCHAR2(12) NOT NULL,
      ROLE_NAME VARCHAR2(20) NOT NULL,
      GRANTED_BY_USER_ID VARCHAR2(12),
      GRANTED_AT DATE DEFAULT SYSDATE NOT NULL,
      CONSTRAINT PK_SYSTEM_USER_ROLE PRIMARY KEY (USER_ID,ROLE_NAME),
      CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES SYSTEM_USER(USER_ID) ON DELETE CASCADE,
      CONSTRAINT FK_USER_ROLE_GRANTER FOREIGN KEY (GRANTED_BY_USER_ID) REFERENCES SYSTEM_USER(USER_ID),
      CONSTRAINT CK_USER_ROLE_NAME CHECK (ROLE_NAME IN ('ADMIN','SUPERVISOR','EMPLOYEE','DOCTOR','VOLUNTEER','ADOPTER','OWNER','DONOR'))
    )]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ROLE_APPLICATION (
      ROLE_APPLICATION_ID VARCHAR2(12) CONSTRAINT PK_ROLE_APPLICATION PRIMARY KEY,
      APPLICANT_USER_ID VARCHAR2(12) NOT NULL,
      REQUESTED_ROLE VARCHAR2(20) NOT NULL,
      DETAILS VARCHAR2(100), OCCUPATION VARCHAR2(80), HIRE_DATE DATE, SALARY NUMBER(12,2),
      STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
      REQUESTED_AT DATE DEFAULT SYSDATE NOT NULL,
      REVIEWED_BY_USER_ID VARCHAR2(12), REVIEWER_ROLE VARCHAR2(20), REVIEWED_AT DATE,
      REVIEW_NOTE VARCHAR2(200),
      CONSTRAINT FK_ROLE_APPLICANT FOREIGN KEY (APPLICANT_USER_ID) REFERENCES SYSTEM_USER(USER_ID) ON DELETE CASCADE,
      CONSTRAINT FK_ROLE_REVIEWER FOREIGN KEY (REVIEWED_BY_USER_ID) REFERENCES SYSTEM_USER(USER_ID),
      CONSTRAINT CK_REQUESTED_ROLE CHECK (REQUESTED_ROLE IN ('SUPERVISOR','EMPLOYEE','DOCTOR','VOLUNTEER','ADOPTER','OWNER','DONOR')),
      CONSTRAINT CK_ROLE_APPLICATION_STATUS CHECK (STATUS IN ('PENDING','APPROVED','REJECTED')),
      CONSTRAINT CK_ROLE_APPLICATION_SALARY CHECK (SALARY IS NULL OR SALARY >= 0)
    )]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

MERGE INTO SYSTEM_USER_ROLE r
USING (SELECT USER_ID,USER_ROLE FROM SYSTEM_USER) u
ON (r.USER_ID=u.USER_ID AND r.ROLE_NAME=u.USER_ROLE)
WHEN NOT MATCHED THEN INSERT (USER_ID,ROLE_NAME) VALUES (u.USER_ID,u.USER_ROLE);

COMMIT;

SELECT USER_ID,ROLE_NAME,GRANTED_AT FROM SYSTEM_USER_ROLE ORDER BY USER_ID,ROLE_NAME;
PROMPT MULTI-ROLE ACCESS MIGRATION COMPLETED
