-- Run with F5 after 13_multi_role_access_migration.sql.
-- Every existing PERSON subtype becomes a switchable dashboard role on that person's one account.

MERGE INTO SYSTEM_USER_ROLE target
USING (
  SELECT DISTINCT USER_ID,ROLE_NAME FROM (
    SELECT u.USER_ID,u.USER_ROLE ROLE_NAME FROM SYSTEM_USER u
    UNION ALL SELECT u.USER_ID,'SUPERVISOR' FROM SYSTEM_USER u JOIN SUPERVISOR r ON r.PERSON_ID=u.PERSON_ID
    UNION ALL SELECT u.USER_ID,'EMPLOYEE' FROM SYSTEM_USER u JOIN EMPLOYEE r ON r.PERSON_ID=u.PERSON_ID
    UNION ALL SELECT u.USER_ID,'DOCTOR' FROM SYSTEM_USER u JOIN DOCTOR r ON r.PERSON_ID=u.PERSON_ID
    UNION ALL SELECT u.USER_ID,'VOLUNTEER' FROM SYSTEM_USER u JOIN VOLUNTEER r ON r.PERSON_ID=u.PERSON_ID
    UNION ALL SELECT u.USER_ID,'ADOPTER' FROM SYSTEM_USER u JOIN ADOPTER r ON r.PERSON_ID=u.PERSON_ID
    UNION ALL SELECT u.USER_ID,'OWNER' FROM SYSTEM_USER u JOIN OWNER r ON r.PERSON_ID=u.PERSON_ID
    UNION ALL SELECT u.USER_ID,'DONOR' FROM SYSTEM_USER u JOIN DONOR r ON r.PERSON_ID=u.PERSON_ID
  )
) source
ON (target.USER_ID=source.USER_ID AND target.ROLE_NAME=source.ROLE_NAME)
WHEN NOT MATCHED THEN
  INSERT (USER_ID,ROLE_NAME,GRANTED_AT)
  VALUES (source.USER_ID,source.ROLE_NAME,SYSDATE);

COMMIT;

SELECT u.PERSON_ID,u.USERNAME,r.ROLE_NAME
FROM SYSTEM_USER u JOIN SYSTEM_USER_ROLE r ON r.USER_ID=u.USER_ID
ORDER BY u.PERSON_ID,r.ROLE_NAME;

PROMPT EXISTING PERSON ROLES SYNCHRONIZED WITH DASHBOARDS
