-- Run once on an existing project database. Safe to rerun.
-- Makes the January-May 2026 demonstration data financially realistic and
-- keeps the overall finance summary and donor totals synchronized.

UPDATE INCOME SET AMOUNT=120000 WHERE SOURCE_ID='IN001';
UPDATE INCOME SET AMOUNT=80000  WHERE SOURCE_ID='IN002';
UPDATE INCOME SET AMOUNT=30000  WHERE SOURCE_ID='IN003';
UPDATE INCOME SET AMOUNT=40000  WHERE SOURCE_ID='IN004';
UPDATE INCOME SET AMOUNT=90000  WHERE SOURCE_ID='IN005';

DECLARE
  v_finance_id FINANCE.FINANCE_ID%TYPE;
BEGIN
  SELECT MIN(FINANCE_ID) INTO v_finance_id FROM FINANCE;

  IF v_finance_id IS NOT NULL THEN
    INSERT INTO FINANCE_EXPENSE(FINANCE_ID,SOURCE_ID)
    SELECT v_finance_id,e.SOURCE_ID
      FROM EXPENSES e
     WHERE NOT EXISTS (
       SELECT 1 FROM FINANCE_EXPENSE fe WHERE fe.SOURCE_ID=e.SOURCE_ID
     );
  END IF;
END;
/

DELETE FROM DONATION d
 WHERE EXISTS (
   SELECT 1
     FROM INCOME i
    WHERE i.SOURCE_ID=d.SOURCE_ID
      AND UPPER(i.SOURCE_NAME) NOT LIKE '%DONATION%'
      AND UPPER(i.SOURCE_NAME) NOT LIKE '%FUND RAISING%'
 );

UPDATE DONOR d
   SET d.DONATION_AMOUNT=(
     SELECT NVL(SUM(i.AMOUNT),0)
       FROM DONATION dn
       JOIN INCOME i ON i.SOURCE_ID=dn.SOURCE_ID
      WHERE dn.DONOR_ID=d.PERSON_ID
   );

CREATE OR REPLACE VIEW VW_FINANCE_SUMMARY AS
SELECT f.OPENING_BALANCE,
       i.TOTAL_INCOME,
       e.TOTAL_EXPENSES,
       i.TOTAL_INCOME-e.TOTAL_EXPENSES NET_ACTIVITY,
       f.OPENING_BALANCE+i.TOTAL_INCOME-e.TOTAL_EXPENSES AVAILABLE_BALANCE
  FROM (SELECT NVL(SUM(CURRENT_BALANCE),0) OPENING_BALANCE FROM FINANCE) f
 CROSS JOIN (
   SELECT NVL(SUM(i.AMOUNT),0) TOTAL_INCOME
     FROM INCOME i
    WHERE EXISTS (SELECT 1 FROM FINANCE_INCOME fi WHERE fi.SOURCE_ID=i.SOURCE_ID)
 ) i
 CROSS JOIN (
   SELECT NVL(SUM(e.AMOUNT),0) TOTAL_EXPENSES
     FROM EXPENSES e
    WHERE EXISTS (SELECT 1 FROM FINANCE_EXPENSE fe WHERE fe.SOURCE_ID=e.SOURCE_ID)
 ) e;

COMMIT;

PROMPT REALISTIC FINANCE DEMO DATA COMPLETED

SELECT OPENING_BALANCE,TOTAL_INCOME,TOTAL_EXPENSES,NET_ACTIVITY,AVAILABLE_BALANCE
  FROM VW_FINANCE_SUMMARY;
