-- Run once on an existing database. Safe to rerun.
-- Adds database-derived pet responsibility, keeps unassigned adoption rows
-- visible, and recompiles database-side completion/exception handling.

CREATE OR REPLACE VIEW VW_PET_DETAILS AS
SELECT p.PET_ID,p.NAME,p.SPECIES,p.BREED,p.DOB,
       TRUNC(MONTHS_BETWEEN(SYSDATE,p.DOB)/12) AGE,p.WEIGHT,
       CASE WHEN l.PET_ID IS NOT NULL THEN 'LOCAL'
            WHEN g.PET_ID IS NOT NULL THEN 'GUEST' END PET_TYPE,
       l.ADOPTION_STATUS,l.IN_TAKE_DATE,g.CHECK_IN_DATE,g.RELEVANT_TIME,
       ps.SHELTER_ID,
       CASE WHEN g.PET_ID IS NOT NULL THEN 'OWNER'
            WHEN ap.STATUS='ADOPTED' THEN 'ADOPTER'
            WHEN ap.STATUS='APPROVED' THEN 'ASSIGNED EMPLOYEE'
            WHEN ss.SUPERVISOR_ID IS NOT NULL THEN 'SHELTER SUPERVISOR'
            ELSE 'UNASSIGNED' END RESPONSIBILITY_TYPE,
       CASE WHEN g.PET_ID IS NOT NULL THEN owner_person.PERSON_ID
            WHEN ap.STATUS='ADOPTED' THEN adopter_person.PERSON_ID
            WHEN ap.STATUS='APPROVED' THEN employee_person.PERSON_ID
            ELSE supervisor_person.PERSON_ID END RESPONSIBLE_ID,
       CASE WHEN g.PET_ID IS NOT NULL THEN owner_person.FIRST_NAME||' '||owner_person.LAST_NAME
            WHEN ap.STATUS='ADOPTED' THEN adopter_person.FIRST_NAME||' '||adopter_person.LAST_NAME
            WHEN ap.STATUS='APPROVED' THEN employee_person.FIRST_NAME||' '||employee_person.LAST_NAME
            WHEN ss.SUPERVISOR_ID IS NOT NULL THEN supervisor_person.FIRST_NAME||' '||supervisor_person.LAST_NAME
            ELSE 'Not assigned' END RESPONSIBLE_NAME
  FROM PET p
  LEFT JOIN LOCAL_PET l ON l.PET_ID=p.PET_ID
  LEFT JOIN GUEST_PET g ON g.PET_ID=p.PET_ID
  LEFT JOIN (SELECT PET_ID,MIN(OWNER_ID) OWNER_ID FROM GUEST_PET_OWNER GROUP BY PET_ID) gpo
    ON gpo.PET_ID=p.PET_ID
  LEFT JOIN PERSON owner_person ON owner_person.PERSON_ID=gpo.OWNER_ID
  LEFT JOIN (
    SELECT LOCAL_PET_ID,ADOPTER_ID,EMPLOYEE_ID,STATUS
      FROM (
        SELECT ap.*,
               ROW_NUMBER() OVER(
                 PARTITION BY LOCAL_PET_ID
                 ORDER BY CASE STATUS WHEN 'ADOPTED' THEN 1 WHEN 'APPROVED' THEN 2 WHEN 'PENDING' THEN 3 ELSE 4 END,
                          APPLY_DATE DESC,ADOPTION_ID DESC
               ) rn
          FROM ADOPTION_PROCESS ap
      )
     WHERE rn=1
  ) ap ON ap.LOCAL_PET_ID=p.PET_ID
  LEFT JOIN PERSON adopter_person ON adopter_person.PERSON_ID=ap.ADOPTER_ID
  LEFT JOIN PERSON employee_person ON employee_person.PERSON_ID=ap.EMPLOYEE_ID
  LEFT JOIN (SELECT PET_ID,MIN(SHELTER_ID) SHELTER_ID FROM PET_SHELTER GROUP BY PET_ID) ps
    ON ps.PET_ID=p.PET_ID
  LEFT JOIN (SELECT SHELTER_ID,MIN(SUPERVISOR_ID) SUPERVISOR_ID FROM SHELTER_SUPERVISION GROUP BY SHELTER_ID) ss
    ON ss.SHELTER_ID=ps.SHELTER_ID
  LEFT JOIN PERSON supervisor_person ON supervisor_person.PERSON_ID=ss.SUPERVISOR_ID;

CREATE OR REPLACE VIEW VW_ADOPTION_APPLICATIONS AS
SELECT ap.ADOPTION_ID,ap.APPLY_DATE,ap.STATUS,
       ap.ADOPTER_ID,ad.FIRST_NAME||' '||ad.LAST_NAME ADOPTER_NAME,
       ap.EMPLOYEE_ID,em.FIRST_NAME||' '||em.LAST_NAME EMPLOYEE_NAME,
       ap.LOCAL_PET_ID,pet.NAME PET_NAME,
       am.SUPERVISOR_ID,su.FIRST_NAME||' '||su.LAST_NAME SUPERVISOR_NAME,
       am.ASSIGN_DATE REVIEW_DATE
  FROM ADOPTION_PROCESS ap
  JOIN PERSON ad ON ad.PERSON_ID=ap.ADOPTER_ID
  LEFT JOIN PERSON em ON em.PERSON_ID=ap.EMPLOYEE_ID
  JOIN PET pet ON pet.PET_ID=ap.LOCAL_PET_ID
  LEFT JOIN ADOPTION_MANAGEMENT am ON am.ADOPTION_ID=ap.ADOPTION_ID
  LEFT JOIN PERSON su ON su.PERSON_ID=am.SUPERVISOR_ID;

CREATE OR REPLACE PROCEDURE PR_MARK_ADOPTED(
  P_ADOPTION_ID VARCHAR2,
  P_EMPLOYEE_ID VARCHAR2
)
AS
  V_PET_ID ADOPTION_PROCESS.LOCAL_PET_ID%TYPE;
BEGIN
  SELECT LOCAL_PET_ID INTO V_PET_ID
    FROM ADOPTION_PROCESS
   WHERE ADOPTION_ID=P_ADOPTION_ID
     AND EMPLOYEE_ID=P_EMPLOYEE_ID
     AND STATUS='APPROVED'
   FOR UPDATE;

  UPDATE ADOPTION_PROCESS SET STATUS='ADOPTED'
   WHERE ADOPTION_ID=P_ADOPTION_ID;

  UPDATE LOCAL_PET SET ADOPTION_STATUS='ADOPTED'
   WHERE PET_ID=V_PET_ID;

  COMMIT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20018,'Only the assigned employee can mark an approved application as adopted');
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

UPDATE LOCAL_PET l
   SET ADOPTION_STATUS=CASE
     WHEN EXISTS (SELECT 1 FROM ADOPTION_PROCESS a WHERE a.LOCAL_PET_ID=l.PET_ID AND a.STATUS='ADOPTED') THEN 'ADOPTED'
     WHEN EXISTS (SELECT 1 FROM ADOPTION_PROCESS a WHERE a.LOCAL_PET_ID=l.PET_ID AND a.STATUS='APPROVED') THEN 'PENDING'
     ELSE ADOPTION_STATUS
   END;

COMMIT;

PROMPT PET RESPONSIBILITY AND ADOPTION WORKFLOW FIX COMPLETED

SELECT PET_ID,NAME,PET_TYPE,ADOPTION_STATUS,RESPONSIBILITY_TYPE,
       RESPONSIBLE_ID,RESPONSIBLE_NAME,SHELTER_ID
  FROM VW_PET_DETAILS
 ORDER BY PET_ID;

SELECT OBJECT_NAME,STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('VW_PET_DETAILS','VW_ADOPTION_APPLICATIONS','PR_MARK_ADOPTED')
 ORDER BY OBJECT_NAME;
