-- Run once on an existing database. Safe to rerun.
-- Replaces the legacy COMPLETED adoption-process state with ADOPTED.

ALTER TABLE ADOPTION_PROCESS DROP CONSTRAINT CK_ADOPTION_STATUS;

UPDATE ADOPTION_PROCESS
   SET STATUS='ADOPTED'
 WHERE STATUS='COMPLETED';

ALTER TABLE ADOPTION_PROCESS ADD CONSTRAINT CK_ADOPTION_STATUS
CHECK (STATUS IN ('PENDING','APPROVED','REJECTED','ADOPTED','CANCELLED'));

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PR_COMPLETE_ADOPTION';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE<>-4043 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE PROCEDURE PR_MARK_ADOPTED(
  P_ADOPTION_ID VARCHAR2,
  P_EMPLOYEE_ID VARCHAR2
)
AS
  V_PET_ID ADOPTION_PROCESS.LOCAL_PET_ID%TYPE;
BEGIN
  SELECT LOCAL_PET_ID INTO V_PET_ID
    FROM ADOPTION_PROCESS
   WHERE ADOPTION_ID=P_ADOPTION_ID
     AND EMPLOYEE_ID=P_EMPLOYEE_ID
     AND STATUS='APPROVED'
   FOR UPDATE;

  UPDATE ADOPTION_PROCESS
     SET STATUS='ADOPTED'
   WHERE ADOPTION_ID=P_ADOPTION_ID;

  UPDATE LOCAL_PET
     SET ADOPTION_STATUS='ADOPTED'
   WHERE PET_ID=V_PET_ID;

  COMMIT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20018,'Only the assigned employee can mark an approved application as adopted');
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

CREATE OR REPLACE VIEW VW_PET_DETAILS AS
SELECT p.PET_ID,p.NAME,p.SPECIES,p.BREED,p.DOB,
       TRUNC(MONTHS_BETWEEN(SYSDATE,p.DOB)/12) AGE,p.WEIGHT,
       CASE WHEN l.PET_ID IS NOT NULL THEN 'LOCAL'
            WHEN g.PET_ID IS NOT NULL THEN 'GUEST' END PET_TYPE,
       l.ADOPTION_STATUS,l.IN_TAKE_DATE,g.CHECK_IN_DATE,g.RELEVANT_TIME,
       ps.SHELTER_ID,
       CASE WHEN g.PET_ID IS NOT NULL THEN 'OWNER'
            WHEN ap.STATUS='ADOPTED' THEN 'ADOPTER'
            WHEN ap.STATUS='APPROVED' THEN 'ASSIGNED EMPLOYEE'
            WHEN ss.SUPERVISOR_ID IS NOT NULL THEN 'SHELTER SUPERVISOR'
            ELSE 'UNASSIGNED' END RESPONSIBILITY_TYPE,
       CASE WHEN g.PET_ID IS NOT NULL THEN owner_person.PERSON_ID
            WHEN ap.STATUS='ADOPTED' THEN adopter_person.PERSON_ID
            WHEN ap.STATUS='APPROVED' THEN employee_person.PERSON_ID
            ELSE supervisor_person.PERSON_ID END RESPONSIBLE_ID,
       CASE WHEN g.PET_ID IS NOT NULL THEN owner_person.FIRST_NAME||' '||owner_person.LAST_NAME
            WHEN ap.STATUS='ADOPTED' THEN adopter_person.FIRST_NAME||' '||adopter_person.LAST_NAME
            WHEN ap.STATUS='APPROVED' THEN employee_person.FIRST_NAME||' '||employee_person.LAST_NAME
            WHEN ss.SUPERVISOR_ID IS NOT NULL THEN supervisor_person.FIRST_NAME||' '||supervisor_person.LAST_NAME
            ELSE 'Not assigned' END RESPONSIBLE_NAME
  FROM PET p
  LEFT JOIN LOCAL_PET l ON l.PET_ID=p.PET_ID
  LEFT JOIN GUEST_PET g ON g.PET_ID=p.PET_ID
  LEFT JOIN (SELECT PET_ID,MIN(OWNER_ID) OWNER_ID FROM GUEST_PET_OWNER GROUP BY PET_ID) gpo
    ON gpo.PET_ID=p.PET_ID
  LEFT JOIN PERSON owner_person ON owner_person.PERSON_ID=gpo.OWNER_ID
  LEFT JOIN (
    SELECT LOCAL_PET_ID,ADOPTER_ID,EMPLOYEE_ID,STATUS
      FROM (
        SELECT ap.*,
               ROW_NUMBER() OVER(
                 PARTITION BY LOCAL_PET_ID
                 ORDER BY CASE STATUS WHEN 'ADOPTED' THEN 1 WHEN 'APPROVED' THEN 2 WHEN 'PENDING' THEN 3 ELSE 4 END,
                          APPLY_DATE DESC,ADOPTION_ID DESC
               ) rn
          FROM ADOPTION_PROCESS ap
      )
     WHERE rn=1
  ) ap ON ap.LOCAL_PET_ID=p.PET_ID
  LEFT JOIN PERSON adopter_person ON adopter_person.PERSON_ID=ap.ADOPTER_ID
  LEFT JOIN PERSON employee_person ON employee_person.PERSON_ID=ap.EMPLOYEE_ID
  LEFT JOIN (SELECT PET_ID,MIN(SHELTER_ID) SHELTER_ID FROM PET_SHELTER GROUP BY PET_ID) ps
    ON ps.PET_ID=p.PET_ID
  LEFT JOIN (SELECT SHELTER_ID,MIN(SUPERVISOR_ID) SUPERVISOR_ID FROM SHELTER_SUPERVISION GROUP BY SHELTER_ID) ss
    ON ss.SHELTER_ID=ps.SHELTER_ID
  LEFT JOIN PERSON supervisor_person ON supervisor_person.PERSON_ID=ss.SUPERVISOR_ID;

COMMIT;

PROMPT ADOPTED STATUS FINAL FIX COMPLETED

SELECT STATUS,COUNT(*) ROW_COUNT
  FROM ADOPTION_PROCESS
 GROUP BY STATUS
 ORDER BY STATUS;

SELECT OBJECT_NAME,STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('PR_MARK_ADOPTED','VW_PET_DETAILS','VW_ADOPTION_APPLICATIONS')
 ORDER BY OBJECT_NAME;
