-- Project Update-3 migration for an existing database.
-- Run as PET_ADMIN with F5 (Run Script). Existing application data is preserved.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME='AUDIT_LOG';
  IF V_COUNT=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE AUDIT_LOG (
      AUDIT_ID NUMBER CONSTRAINT PK_AUDIT_LOG PRIMARY KEY,
      EVENT_TYPE VARCHAR2(50) NOT NULL,
      ENTITY_NAME VARCHAR2(50) NOT NULL,
      ENTITY_ID VARCHAR2(12),
      OLD_VALUE VARCHAR2(100),
      NEW_VALUE VARCHAR2(100),
      CHANGED_BY VARCHAR2(128) NOT NULL,
      CHANGED_AT DATE DEFAULT SYSDATE NOT NULL
    )';
  END IF;

  SELECT COUNT(*) INTO V_COUNT FROM USER_SEQUENCES WHERE SEQUENCE_NAME='AUDIT_LOG_SEQ';
  IF V_COUNT=0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_LOG_ID
BEFORE INSERT ON AUDIT_LOG
FOR EACH ROW
WHEN (NEW.AUDIT_ID IS NULL)
BEGIN
  SELECT AUDIT_LOG_SEQ.NEXTVAL INTO :NEW.AUDIT_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_ADOPTION_STATUS_AUDIT
AFTER UPDATE OF STATUS ON ADOPTION_PROCESS
FOR EACH ROW
WHEN (OLD.STATUS <> NEW.STATUS)
BEGIN
  INSERT INTO AUDIT_LOG(EVENT_TYPE,ENTITY_NAME,ENTITY_ID,OLD_VALUE,NEW_VALUE,CHANGED_BY,CHANGED_AT)
  VALUES('ADOPTION_STATUS_CHANGED','ADOPTION_PROCESS',:NEW.ADOPTION_ID,
         :OLD.STATUS,:NEW.STATUS,USER,SYSDATE);
END;
/

COMMIT;

SELECT OBJECT_NAME,OBJECT_TYPE,STATUS FROM USER_OBJECTS
WHERE OBJECT_NAME IN ('AUDIT_LOG','AUDIT_LOG_SEQ','TRG_AUDIT_LOG_ID','TRG_ADOPTION_STATUS_AUDIT')
ORDER BY OBJECT_TYPE,OBJECT_NAME;

PROMPT PROJECT UPDATE-3 DATABASE MIGRATION COMPLETED
EXIT
