-- Adds the real application user to trigger-generated adoption history.
-- Run once as PET_ADMIN with F5. Existing audit rows remain available.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

CREATE OR REPLACE PACKAGE PETCARE_AUDIT_CONTEXT AS
  G_ACTOR_PERSON_ID VARCHAR2(12);
  PROCEDURE SET_ACTOR(P_PERSON_ID VARCHAR2);
  PROCEDURE CLEAR_ACTOR;
END PETCARE_AUDIT_CONTEXT;
/

CREATE OR REPLACE PACKAGE BODY PETCARE_AUDIT_CONTEXT AS
  PROCEDURE SET_ACTOR(P_PERSON_ID VARCHAR2) AS
  BEGIN
    G_ACTOR_PERSON_ID:=P_PERSON_ID;
  END;

  PROCEDURE CLEAR_ACTOR AS
  BEGIN
    G_ACTOR_PERSON_ID:=NULL;
  END;
END PETCARE_AUDIT_CONTEXT;
/

CREATE OR REPLACE TRIGGER TRG_ADOPTION_STATUS_AUDIT
AFTER UPDATE OF STATUS ON ADOPTION_PROCESS
FOR EACH ROW
WHEN (OLD.STATUS <> NEW.STATUS)
BEGIN
  INSERT INTO AUDIT_LOG(EVENT_TYPE,ENTITY_NAME,ENTITY_ID,OLD_VALUE,NEW_VALUE,CHANGED_BY,CHANGED_AT)
  VALUES('ADOPTION_STATUS_CHANGED','ADOPTION_PROCESS',:NEW.ADOPTION_ID,
         :OLD.STATUS,:NEW.STATUS,
         NVL(PETCARE_AUDIT_CONTEXT.G_ACTOR_PERSON_ID,USER),SYSDATE);
END;
/

COMMIT;

SELECT OBJECT_NAME,OBJECT_TYPE,STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME IN ('PETCARE_AUDIT_CONTEXT','TRG_ADOPTION_STATUS_AUDIT')
ORDER BY OBJECT_TYPE,OBJECT_NAME;

PROMPT DETAILED ADOPTION ACTIVITY HISTORY COMPLETED
EXIT
