-- Adds a login for the existing demonstration Volunteer P008 (Arif Khan).
-- Safe to run on an existing database; it does not replace a real account.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  V_USER_ID SYSTEM_USER.USER_ID%TYPE;
  V_USERNAME_COUNT NUMBER;
BEGIN
  SELECT MIN(USER_ID) INTO V_USER_ID
  FROM SYSTEM_USER
  WHERE PERSON_ID='P008';

  IF V_USER_ID IS NULL THEN
    SELECT COUNT(*) INTO V_USERNAME_COUNT
    FROM SYSTEM_USER
    WHERE USERNAME='volunteer';

    IF V_USERNAME_COUNT>0 THEN
      RAISE_APPLICATION_ERROR(-20041,'Username volunteer is already used by another person');
    END IF;

    V_USER_ID:='UV'||SUBSTR(RAWTOHEX(SYS_GUID()),1,10);

    INSERT INTO SYSTEM_USER(
      USER_ID,PERSON_ID,USERNAME,PASSWORD_HASH,USER_ROLE,USER_STATUS
    ) VALUES(
      V_USER_ID,'P008','volunteer',
      '$2b$10$epynEfs4psB00OHzoxOiH.V9QkT5PaOlBozO1NBbo8UzYv4CZwQD.',
      'VOLUNTEER','ACTIVE'
    );
  END IF;

  MERGE INTO SYSTEM_USER_ROLE target
  USING (SELECT V_USER_ID USER_ID,'VOLUNTEER' ROLE_NAME FROM DUAL) source
  ON (target.USER_ID=source.USER_ID AND target.ROLE_NAME=source.ROLE_NAME)
  WHEN NOT MATCHED THEN
    INSERT(USER_ID,ROLE_NAME) VALUES(source.USER_ID,source.ROLE_NAME);

  -- P008 is also a DONOR in the ER data, so the same account can switch roles.
  MERGE INTO SYSTEM_USER_ROLE target
  USING (SELECT V_USER_ID USER_ID,'DONOR' ROLE_NAME FROM DUAL
         WHERE EXISTS (SELECT 1 FROM DONOR WHERE PERSON_ID='P008')) source
  ON (target.USER_ID=source.USER_ID AND target.ROLE_NAME=source.ROLE_NAME)
  WHEN NOT MATCHED THEN
    INSERT(USER_ID,ROLE_NAME) VALUES(source.USER_ID,source.ROLE_NAME);
END;
/

COMMIT;

SELECT u.USERNAME,u.USER_STATUS,r.ROLE_NAME,p.FIRST_NAME||' '||p.LAST_NAME FULL_NAME
FROM SYSTEM_USER u
JOIN SYSTEM_USER_ROLE r ON r.USER_ID=u.USER_ID
JOIN PERSON p ON p.PERSON_ID=u.PERSON_ID
WHERE u.PERSON_ID='P008'
ORDER BY r.ROLE_NAME;

PROMPT VOLUNTEER DEMO ACCOUNT COMPLETED
EXIT
