-- Rescue-to-pet intake workflow. Safe to run more than once.
-- Adds rescue status tracking, generated ID sequences, rescued-pet links,
-- and reporting columns used by the application.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME='RESCUE'
     AND COLUMN_NAME='STATUS';

  IF v_count=0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE RESCUE ADD (
        STATUS VARCHAR2(30) DEFAULT 'PENDING_INTAKE' NOT NULL
      )
    ]';
  END IF;
END;
/

UPDATE RESCUE
   SET STATUS='INTAKE_COMPLETED'
 WHERE STATUS IS NULL;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME='RESCUE'
     AND CONSTRAINT_NAME='CK_RESCUE_STATUS';

  IF v_count=0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE RESCUE ADD CONSTRAINT CK_RESCUE_STATUS
      CHECK (STATUS IN ('PENDING_INTAKE','INTAKE_IN_PROGRESS','INTAKE_COMPLETED','CANCELLED'))
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME='PET'
     AND COLUMN_NAME='GENDER';

  IF v_count=0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE PET ADD (
        GENDER VARCHAR2(20)
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME='PET'
     AND CONSTRAINT_NAME='CK_PET_GENDER';

  IF v_count=0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE PET ADD CONSTRAINT CK_PET_GENDER
      CHECK (GENDER IS NULL OR GENDER IN ('MALE','FEMALE','UNKNOWN'))
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME='RESCUE_ID_SEQ';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE RESCUE_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME='LOCAL_PET_ID_SEQ';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE LOCAL_PET_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='RESCUE_PET';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE RESCUE_PET (
        RESCUE_ID VARCHAR2(12) NOT NULL,
        PET_ID VARCHAR2(12) NOT NULL,
        INTAKE_DATE DATE NOT NULL,
        REGISTERED_BY VARCHAR2(12) NOT NULL,
        CONSTRAINT PK_RESCUE_PET PRIMARY KEY (RESCUE_ID,PET_ID),
        CONSTRAINT FK_RESCUE_PET_RESCUE FOREIGN KEY (RESCUE_ID)
          REFERENCES RESCUE (RESCUE_ID),
        CONSTRAINT FK_RESCUE_PET_PET FOREIGN KEY (PET_ID)
          REFERENCES PET (PET_ID),
        CONSTRAINT FK_RESCUE_PET_REGISTERED_BY FOREIGN KEY (REGISTERED_BY)
          REFERENCES PERSON (PERSON_ID)
      )
    ]';
  END IF;
END;
/

CREATE OR REPLACE VIEW VW_RESCUE_DETAILS AS
SELECT r.RESCUE_ID,
       r.RESCUE_DATE,
       r.LOCATION,
       r.STATUS INTAKE_STATUS,
       rs.SHELTER_ID,
       s.ROOM_TYPE SHELTER_ROOM_TYPE,
       ss.SUPERVISOR_ID,
       supervisor_person.FIRST_NAME||' '||supervisor_person.LAST_NAME SUPERVISOR_NAME,
       vr.VOLUNTEER_ID,
       volunteer_person.FIRST_NAME||' '||volunteer_person.LAST_NAME VOLUNTEER_NAME,
       pets.PET_IDS,
       pets.PET_NAMES,
       pets.INTAKE_DATE
  FROM RESCUE r
  JOIN RESCUE_SHELTER rs ON rs.RESCUE_ID=r.RESCUE_ID
  JOIN SHELTER s ON s.SHELTER_ID=rs.SHELTER_ID
  JOIN VOLUNTEER_RESCUE vr ON vr.RESCUE_ID=r.RESCUE_ID
  JOIN PERSON volunteer_person ON volunteer_person.PERSON_ID=vr.VOLUNTEER_ID
  LEFT JOIN SHELTER_SUPERVISION ss ON ss.SHELTER_ID=rs.SHELTER_ID
  LEFT JOIN PERSON supervisor_person ON supervisor_person.PERSON_ID=ss.SUPERVISOR_ID
  LEFT JOIN (
    SELECT rp.RESCUE_ID,
           LISTAGG(rp.PET_ID,', ') WITHIN GROUP (ORDER BY rp.PET_ID) PET_IDS,
           LISTAGG(p.NAME,', ') WITHIN GROUP (ORDER BY rp.PET_ID) PET_NAMES,
           MAX(rp.INTAKE_DATE) INTAKE_DATE
      FROM RESCUE_PET rp
      JOIN PET p ON p.PET_ID=rp.PET_ID
     GROUP BY rp.RESCUE_ID
  ) pets ON pets.RESCUE_ID=r.RESCUE_ID;

CREATE OR REPLACE VIEW VW_PET_DETAILS AS
SELECT p.PET_ID,p.NAME,p.SPECIES,p.BREED,p.DOB,p.GENDER,
       TRUNC(MONTHS_BETWEEN(SYSDATE,p.DOB)/12) AGE,p.WEIGHT,
       CASE WHEN l.PET_ID IS NOT NULL THEN 'LOCAL'
            WHEN g.PET_ID IS NOT NULL THEN 'GUEST' END PET_TYPE,
       l.ADOPTION_STATUS,l.IN_TAKE_DATE,g.CHECK_IN_DATE,g.RELEVANT_TIME,
       ps.SHELTER_ID,
       source_rescue.RESCUE_ID SOURCE_RESCUE_ID,
       CASE WHEN g.PET_ID IS NOT NULL THEN 'OWNER'
            WHEN ap.STATUS='ADOPTED' THEN 'ADOPTER'
            WHEN ap.STATUS='APPROVED' THEN 'ASSIGNED EMPLOYEE'
            WHEN ss.SUPERVISOR_ID IS NOT NULL THEN 'SHELTER SUPERVISOR'
            ELSE 'UNASSIGNED' END RESPONSIBILITY_TYPE,
       CASE WHEN g.PET_ID IS NOT NULL THEN owner_person.PERSON_ID
            WHEN ap.STATUS='ADOPTED' THEN adopter_person.PERSON_ID
            WHEN ap.STATUS='APPROVED' THEN employee_person.PERSON_ID
            ELSE supervisor_person.PERSON_ID END RESPONSIBLE_ID,
       CASE WHEN g.PET_ID IS NOT NULL THEN owner_person.FIRST_NAME||' '||owner_person.LAST_NAME
            WHEN ap.STATUS='ADOPTED' THEN adopter_person.FIRST_NAME||' '||adopter_person.LAST_NAME
            WHEN ap.STATUS='APPROVED' THEN employee_person.FIRST_NAME||' '||employee_person.LAST_NAME
            WHEN ss.SUPERVISOR_ID IS NOT NULL THEN supervisor_person.FIRST_NAME||' '||supervisor_person.LAST_NAME
            ELSE 'Not assigned' END RESPONSIBLE_NAME
  FROM PET p
  LEFT JOIN LOCAL_PET l ON l.PET_ID=p.PET_ID
  LEFT JOIN GUEST_PET g ON g.PET_ID=p.PET_ID
  LEFT JOIN (SELECT PET_ID,MIN(OWNER_ID) OWNER_ID FROM GUEST_PET_OWNER GROUP BY PET_ID) gpo
    ON gpo.PET_ID=p.PET_ID
  LEFT JOIN PERSON owner_person ON owner_person.PERSON_ID=gpo.OWNER_ID
  LEFT JOIN (
    SELECT LOCAL_PET_ID,ADOPTER_ID,EMPLOYEE_ID,STATUS
      FROM (
        SELECT ap.*,
               ROW_NUMBER() OVER(
                 PARTITION BY LOCAL_PET_ID
                 ORDER BY CASE STATUS WHEN 'ADOPTED' THEN 1 WHEN 'APPROVED' THEN 2 WHEN 'PENDING' THEN 3 ELSE 4 END,
                          APPLY_DATE DESC,ADOPTION_ID DESC
               ) rn
          FROM ADOPTION_PROCESS ap
      )
     WHERE rn=1
  ) ap ON ap.LOCAL_PET_ID=p.PET_ID
  LEFT JOIN PERSON adopter_person ON adopter_person.PERSON_ID=ap.ADOPTER_ID
  LEFT JOIN PERSON employee_person ON employee_person.PERSON_ID=ap.EMPLOYEE_ID
  LEFT JOIN (SELECT PET_ID,MIN(SHELTER_ID) SHELTER_ID FROM PET_SHELTER GROUP BY PET_ID) ps
    ON ps.PET_ID=p.PET_ID
  LEFT JOIN (SELECT SHELTER_ID,MIN(SUPERVISOR_ID) SUPERVISOR_ID FROM SHELTER_SUPERVISION GROUP BY SHELTER_ID) ss
    ON ss.SHELTER_ID=ps.SHELTER_ID
  LEFT JOIN PERSON supervisor_person ON supervisor_person.PERSON_ID=ss.SUPERVISOR_ID
  LEFT JOIN (SELECT PET_ID,MIN(RESCUE_ID) RESCUE_ID FROM RESCUE_PET GROUP BY PET_ID) source_rescue
    ON source_rescue.PET_ID=p.PET_ID;

COMMIT;

PROMPT RESCUE INTAKE WORKFLOW MIGRATION COMPLETED

SELECT OBJECT_NAME,OBJECT_TYPE,STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('RESCUE_PET','RESCUE_ID_SEQ','LOCAL_PET_ID_SEQ','VW_RESCUE_DETAILS','VW_PET_DETAILS')
 ORDER BY OBJECT_TYPE,OBJECT_NAME;
