-- Database-owned local pet ID generation for rescued pets.
-- If PET.PET_ID is inserted as NULL, Oracle assigns the next unused LP###.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM USER_SEQUENCES
   WHERE SEQUENCE_NAME='LOCAL_PET_ID_SEQ';

  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE LOCAL_PET_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PET_AUTO_LOCAL_ID
BEFORE INSERT ON PET
FOR EACH ROW
WHEN (NEW.PET_ID IS NULL)
DECLARE
  v_next NUMBER;
  v_candidate PET.PET_ID%TYPE;
  v_count NUMBER;
BEGIN
  LOOP
    SELECT LOCAL_PET_ID_SEQ.NEXTVAL INTO v_next FROM DUAL;
    v_candidate := 'LP' || LPAD(v_next,3,'0');

    SELECT COUNT(*) INTO v_count
      FROM PET
     WHERE PET_ID=v_candidate;

    IF v_count=0 THEN
      :NEW.PET_ID := v_candidate;
      EXIT;
    END IF;
  END LOOP;
END;
/

COMMIT;

PROMPT PET AUTO LOCAL ID TRIGGER MIGRATION COMPLETED

SELECT OBJECT_NAME,OBJECT_TYPE,STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME='TRG_PET_AUTO_LOCAL_ID'
 ORDER BY OBJECT_TYPE,OBJECT_NAME;
