-- Database-owned IDs for people, users and medical records.
-- NULL IDs are assigned as the next unused P###, U### or MR### value.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME='PERSON_ID_SEQ';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE PERSON_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SYSTEM_USER_ID_SEQ';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SYSTEM_USER_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME='MEDICAL_RECORD_ID_SEQ';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE MEDICAL_RECORD_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PERSON_AUTO_ID
BEFORE INSERT ON PERSON
FOR EACH ROW
WHEN (NEW.PERSON_ID IS NULL)
DECLARE
  v_next NUMBER;
  v_candidate PERSON.PERSON_ID%TYPE;
  v_count NUMBER;
BEGIN
  LOOP
    SELECT PERSON_ID_SEQ.NEXTVAL INTO v_next FROM DUAL;
    v_candidate := 'P' || LPAD(v_next,3,'0');
    SELECT COUNT(*) INTO v_count FROM PERSON WHERE PERSON_ID=v_candidate;
    IF v_count=0 THEN
      :NEW.PERSON_ID := v_candidate;
      EXIT;
    END IF;
  END LOOP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SYSTEM_USER_AUTO_ID
BEFORE INSERT ON SYSTEM_USER
FOR EACH ROW
WHEN (NEW.USER_ID IS NULL)
DECLARE
  v_next NUMBER;
  v_candidate SYSTEM_USER.USER_ID%TYPE;
  v_count NUMBER;
BEGIN
  LOOP
    SELECT SYSTEM_USER_ID_SEQ.NEXTVAL INTO v_next FROM DUAL;
    v_candidate := 'U' || LPAD(v_next,3,'0');
    SELECT COUNT(*) INTO v_count FROM SYSTEM_USER WHERE USER_ID=v_candidate;
    IF v_count=0 THEN
      :NEW.USER_ID := v_candidate;
      EXIT;
    END IF;
  END LOOP;
END;
/

CREATE OR REPLACE TRIGGER TRG_MEDICAL_RECORD_AUTO_ID
BEFORE INSERT ON MEDICAL_RECORD
FOR EACH ROW
WHEN (NEW.RECORD_ID IS NULL)
DECLARE
  v_next NUMBER;
  v_candidate MEDICAL_RECORD.RECORD_ID%TYPE;
  v_count NUMBER;
BEGIN
  LOOP
    SELECT MEDICAL_RECORD_ID_SEQ.NEXTVAL INTO v_next FROM DUAL;
    v_candidate := 'MR' || LPAD(v_next,3,'0');
    SELECT COUNT(*) INTO v_count FROM MEDICAL_RECORD WHERE RECORD_ID=v_candidate;
    IF v_count=0 THEN
      :NEW.RECORD_ID := v_candidate;
      EXIT;
    END IF;
  END LOOP;
END;
/

CREATE OR REPLACE TRIGGER TRG_ROLE_APP_NO_OWNER
BEFORE INSERT OR UPDATE OF REQUESTED_ROLE ON ROLE_APPLICATION
FOR EACH ROW
BEGIN
  IF :NEW.REQUESTED_ROLE='OWNER' THEN
    RAISE_APPLICATION_ERROR(-20041,'Owner role cannot be requested through role applications.');
  END IF;
END;
/

COMMIT;

PROMPT ID TRIGGER MIGRATION COMPLETED

SELECT OBJECT_NAME,OBJECT_TYPE,STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN (
   'PERSON_ID_SEQ','SYSTEM_USER_ID_SEQ','MEDICAL_RECORD_ID_SEQ',
   'TRG_PERSON_AUTO_ID','TRG_SYSTEM_USER_AUTO_ID',
   'TRG_MEDICAL_RECORD_AUTO_ID','TRG_ROLE_APP_NO_OWNER'
 )
 ORDER BY OBJECT_TYPE,OBJECT_NAME;
