-- Human-readable generated IDs for direct pet entry, adoption applications
-- and audit display support.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME='GUEST_PET_ID_SEQ';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE GUEST_PET_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME='ADOPTION_ID_SEQ';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ADOPTION_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;
END;
/

CREATE OR REPLACE PACKAGE PETCARE_ID_CONTEXT AS
  PROCEDURE SET_PET_PREFIX(P_PREFIX VARCHAR2);
  PROCEDURE CLEAR_PET_PREFIX;
  FUNCTION PET_PREFIX RETURN VARCHAR2;
END PETCARE_ID_CONTEXT;
/

CREATE OR REPLACE PACKAGE BODY PETCARE_ID_CONTEXT AS
  G_PET_PREFIX VARCHAR2(2);

  PROCEDURE SET_PET_PREFIX(P_PREFIX VARCHAR2) AS
  BEGIN
    G_PET_PREFIX := UPPER(P_PREFIX);
  END;

  PROCEDURE CLEAR_PET_PREFIX AS
  BEGIN
    G_PET_PREFIX := NULL;
  END;

  FUNCTION PET_PREFIX RETURN VARCHAR2 AS
  BEGIN
    RETURN NVL(G_PET_PREFIX,'LP');
  END;
END PETCARE_ID_CONTEXT;
/

CREATE OR REPLACE TRIGGER TRG_PET_AUTO_LOCAL_ID
BEFORE INSERT ON PET
FOR EACH ROW
WHEN (NEW.PET_ID IS NULL)
DECLARE
  v_next NUMBER;
  v_prefix VARCHAR2(2);
  v_candidate PET.PET_ID%TYPE;
  v_count NUMBER;
BEGIN
  v_prefix := PETCARE_ID_CONTEXT.PET_PREFIX;
  IF v_prefix NOT IN ('LP','GP') THEN
    v_prefix := 'LP';
  END IF;

  LOOP
    IF v_prefix='GP' THEN
      SELECT GUEST_PET_ID_SEQ.NEXTVAL INTO v_next FROM DUAL;
    ELSE
      SELECT LOCAL_PET_ID_SEQ.NEXTVAL INTO v_next FROM DUAL;
    END IF;

    v_candidate := v_prefix || LPAD(v_next,3,'0');
    SELECT COUNT(*) INTO v_count FROM PET WHERE PET_ID=v_candidate;

    IF v_count=0 THEN
      :NEW.PET_ID := v_candidate;
      EXIT;
    END IF;
  END LOOP;
END;
/

CREATE OR REPLACE TRIGGER TRG_ADOPTION_AUTO_ID
BEFORE INSERT ON ADOPTION_PROCESS
FOR EACH ROW
WHEN (NEW.ADOPTION_ID IS NULL)
DECLARE
  v_next NUMBER;
  v_candidate ADOPTION_PROCESS.ADOPTION_ID%TYPE;
  v_count NUMBER;
BEGIN
  LOOP
    SELECT ADOPTION_ID_SEQ.NEXTVAL INTO v_next FROM DUAL;
    v_candidate := 'AD' || LPAD(v_next,3,'0');
    SELECT COUNT(*) INTO v_count FROM ADOPTION_PROCESS WHERE ADOPTION_ID=v_candidate;
    IF v_count=0 THEN
      :NEW.ADOPTION_ID := v_candidate;
      EXIT;
    END IF;
  END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE PR_SUBMIT_ADOPTION(
  P_ADOPTER_ID VARCHAR2,
  P_LOCAL_PET_ID VARCHAR2,
  P_ADOPTION_ID OUT VARCHAR2
)
AS
  V_AVAILABLE NUMBER;
  V_DUPLICATE NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_AVAILABLE
  FROM LOCAL_PET
  WHERE PET_ID=P_LOCAL_PET_ID AND ADOPTION_STATUS='AVAILABLE';

  IF V_AVAILABLE=0 THEN
    RAISE_APPLICATION_ERROR(-20011,'This pet is not currently available for adoption');
  END IF;

  SELECT COUNT(*) INTO V_DUPLICATE
  FROM ADOPTION_PROCESS
  WHERE ADOPTER_ID=P_ADOPTER_ID
    AND LOCAL_PET_ID=P_LOCAL_PET_ID
    AND STATUS IN ('PENDING','APPROVED');

  IF V_DUPLICATE>0 THEN
    RAISE_APPLICATION_ERROR(-20012,'You already have an active application for this pet');
  END IF;

  INSERT INTO ADOPTION_PROCESS(
    ADOPTION_ID,ADOPTER_ID,EMPLOYEE_ID,LOCAL_PET_ID,APPLY_DATE,STATUS
  ) VALUES(
    NULL,P_ADOPTER_ID,NULL,P_LOCAL_PET_ID,TRUNC(SYSDATE),'PENDING'
  )
  RETURNING ADOPTION_ID INTO P_ADOPTION_ID;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

COMMIT;

PROMPT PET AND ADOPTION ID CLEANUP MIGRATION COMPLETED

SELECT OBJECT_NAME,OBJECT_TYPE,STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN (
   'GUEST_PET_ID_SEQ','ADOPTION_ID_SEQ','PETCARE_ID_CONTEXT',
   'TRG_PET_AUTO_LOCAL_ID','TRG_ADOPTION_AUTO_ID','PR_SUBMIT_ADOPTION'
 )
 ORDER BY OBJECT_TYPE,OBJECT_NAME;
