-- Adoption review must accept any active account with an approved EMPLOYEE role,
-- not only accounts whose primary/current stored USER_ROLE is EMPLOYEE.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

CREATE OR REPLACE PROCEDURE PR_REVIEW_ADOPTION(
  P_ADOPTION_ID VARCHAR2,
  P_SUPERVISOR_ID VARCHAR2,
  P_DECISION VARCHAR2,
  P_EMPLOYEE_ID VARCHAR2 DEFAULT NULL
)
AS
  V_STATUS ADOPTION_PROCESS.STATUS%TYPE;
  V_PET_ID ADOPTION_PROCESS.LOCAL_PET_ID%TYPE;
  V_EMPLOYEE NUMBER;
BEGIN
  SELECT STATUS,LOCAL_PET_ID INTO V_STATUS,V_PET_ID
  FROM ADOPTION_PROCESS
  WHERE ADOPTION_ID=P_ADOPTION_ID
  FOR UPDATE;

  IF V_STATUS<>'PENDING' THEN
    RAISE_APPLICATION_ERROR(-20013,'Only a pending application can be reviewed');
  END IF;

  IF P_DECISION NOT IN ('APPROVED','REJECTED') THEN
    RAISE_APPLICATION_ERROR(-20014,'Decision must be APPROVED or REJECTED');
  END IF;

  IF P_DECISION='APPROVED' THEN
    IF P_EMPLOYEE_ID IS NULL THEN
      RAISE_APPLICATION_ERROR(-20015,'Assign an employee before approving');
    END IF;

    SELECT COUNT(*) INTO V_EMPLOYEE
    FROM EMPLOYEE e
    JOIN SYSTEM_USER u ON u.PERSON_ID=e.PERSON_ID
    JOIN SYSTEM_USER_ROLE ur ON ur.USER_ID=u.USER_ID
    WHERE e.PERSON_ID=P_EMPLOYEE_ID
      AND u.USER_STATUS='ACTIVE'
      AND ur.ROLE_NAME='EMPLOYEE';

    IF V_EMPLOYEE=0 THEN
      RAISE_APPLICATION_ERROR(-20016,'The selected employee does not have an active employee account');
    END IF;

    UPDATE ADOPTION_PROCESS
    SET STATUS='APPROVED',EMPLOYEE_ID=P_EMPLOYEE_ID
    WHERE ADOPTION_ID=P_ADOPTION_ID;

    UPDATE LOCAL_PET SET ADOPTION_STATUS='PENDING' WHERE PET_ID=V_PET_ID;
  ELSE
    UPDATE ADOPTION_PROCESS
    SET STATUS='REJECTED',EMPLOYEE_ID=NULL
    WHERE ADOPTION_ID=P_ADOPTION_ID;
  END IF;

  MERGE INTO ADOPTION_MANAGEMENT target
  USING (SELECT P_ADOPTION_ID ADOPTION_ID FROM DUAL) source
  ON (target.ADOPTION_ID=source.ADOPTION_ID)
  WHEN MATCHED THEN UPDATE SET
    target.SUPERVISOR_ID=P_SUPERVISOR_ID,
    target.ASSIGN_DATE=TRUNC(SYSDATE),
    target.SALARY=NULL
  WHEN NOT MATCHED THEN INSERT(
    SUPERVISOR_ID,ADOPTION_ID,ASSIGN_DATE,SALARY
  ) VALUES(
    P_SUPERVISOR_ID,P_ADOPTION_ID,TRUNC(SYSDATE),NULL
  );

  COMMIT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20017,'Adoption application was not found');
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

COMMIT;

PROMPT EMPLOYEE ASSIGNMENT ROLE CHECK FIX COMPLETED

SELECT OBJECT_NAME,OBJECT_TYPE,STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME='PR_REVIEW_ADOPTION'
 ORDER BY OBJECT_TYPE,OBJECT_NAME;
