-- Normalize old random PERSON_ID values to the project P### format.
-- Run once on an existing database where people were created before
-- TRG_PERSON_AUTO_ID was installed.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PERSON_ID_REMAP PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  FOR c IN (
    SELECT CONSTRAINT_NAME,TABLE_NAME
      FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_TYPE='R'
       AND STATUS='DISABLED'
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE '||c.TABLE_NAME||' ENABLE CONSTRAINT '||c.CONSTRAINT_NAME;
    EXCEPTION
      WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/

CREATE TABLE PERSON_ID_REMAP (
  OLD_PERSON_ID VARCHAR2(12) PRIMARY KEY,
  NEW_PERSON_ID VARCHAR2(12) NOT NULL UNIQUE
);

DECLARE
  v_base NUMBER;
BEGIN
  SELECT NVL(MAX(TO_NUMBER(SUBSTR(PERSON_ID,2))),0)
    INTO v_base
    FROM PERSON
   WHERE REGEXP_LIKE(PERSON_ID,'^P[0-9]{3}$');

  INSERT INTO PERSON_ID_REMAP(OLD_PERSON_ID,NEW_PERSON_ID)
  SELECT PERSON_ID,
         'P' || LPAD(v_base + ROW_NUMBER() OVER (ORDER BY PERSON_ID),3,'0')
    FROM PERSON
   WHERE NOT REGEXP_LIKE(PERSON_ID,'^P[0-9]{3}$');
END;
/

DECLARE
  v_sql VARCHAR2(4000);
  v_audit_log_count NUMBER;
BEGIN
  FOR c IN (
    SELECT CONSTRAINT_NAME,TABLE_NAME
      FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_TYPE='R'
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE '||c.TABLE_NAME||' DISABLE CONSTRAINT '||c.CONSTRAINT_NAME;
  END LOOP;

  FOR col IN (
    SELECT DISTINCT child.TABLE_NAME,child.COLUMN_NAME
      FROM USER_CONSTRAINTS fk
      JOIN USER_CONS_COLUMNS child
        ON child.CONSTRAINT_NAME=fk.CONSTRAINT_NAME
      JOIN USER_CONSTRAINTS parent
        ON parent.CONSTRAINT_NAME=fk.R_CONSTRAINT_NAME
     WHERE fk.CONSTRAINT_TYPE='R'
       AND parent.TABLE_NAME IN (
         'PERSON','DOCTOR','VOLUNTEER','SUPERVISOR','ADOPTER','EMPLOYEE','DONOR','OWNER'
       )
       AND child.POSITION=1
  ) LOOP
    v_sql :=
      'UPDATE '||col.TABLE_NAME||' t SET '||col.COLUMN_NAME||
      '=(SELECT m.NEW_PERSON_ID FROM PERSON_ID_REMAP m WHERE m.OLD_PERSON_ID=t.'||col.COLUMN_NAME||') '||
      'WHERE EXISTS (SELECT 1 FROM PERSON_ID_REMAP m WHERE m.OLD_PERSON_ID=t.'||col.COLUMN_NAME||')';
    EXECUTE IMMEDIATE v_sql;
  END LOOP;

  SELECT COUNT(*) INTO v_audit_log_count
    FROM USER_TABLES
   WHERE TABLE_NAME='AUDIT_LOG';

  IF v_audit_log_count=1 THEN
    EXECUTE IMMEDIATE
      'UPDATE AUDIT_LOG al '||
      'SET CHANGED_BY=(SELECT m.NEW_PERSON_ID FROM PERSON_ID_REMAP m WHERE m.OLD_PERSON_ID=al.CHANGED_BY) '||
      'WHERE EXISTS (SELECT 1 FROM PERSON_ID_REMAP m WHERE m.OLD_PERSON_ID=al.CHANGED_BY)';
  END IF;

  UPDATE PERSON p
     SET PERSON_ID=(SELECT m.NEW_PERSON_ID FROM PERSON_ID_REMAP m WHERE m.OLD_PERSON_ID=p.PERSON_ID)
   WHERE EXISTS (SELECT 1 FROM PERSON_ID_REMAP m WHERE m.OLD_PERSON_ID=p.PERSON_ID);

  FOR c IN (
    SELECT CONSTRAINT_NAME,TABLE_NAME
      FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_TYPE='R'
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE '||c.TABLE_NAME||' ENABLE CONSTRAINT '||c.CONSTRAINT_NAME;
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN
    FOR c IN (
      SELECT CONSTRAINT_NAME,TABLE_NAME
        FROM USER_CONSTRAINTS
       WHERE CONSTRAINT_TYPE='R'
         AND STATUS='DISABLED'
    ) LOOP
      BEGIN
        EXECUTE IMMEDIATE 'ALTER TABLE '||c.TABLE_NAME||' ENABLE CONSTRAINT '||c.CONSTRAINT_NAME;
      EXCEPTION
        WHEN OTHERS THEN NULL;
      END;
    END LOOP;
    RAISE;
END;
/

COMMIT;

PROMPT PERSON IDS NORMALIZED

SELECT OLD_PERSON_ID,NEW_PERSON_ID
  FROM PERSON_ID_REMAP
 ORDER BY NEW_PERSON_ID;

DROP TABLE PERSON_ID_REMAP PURGE;
