-- 1. View all persons
SELECT *
FROM PERSON
ORDER BY PERSON_ID;

-- 2. View all pets
SELECT *
FROM PET
ORDER BY PET_ID;

-- 3. Count total pets
SELECT COUNT(*) AS TOTAL_PETS
FROM PET;

-- 4. Count local pets
SELECT COUNT(*) AS TOTAL_LOCAL_PETS
FROM LOCAL_PET;

-- 5. Count guest pets
SELECT COUNT(*) AS TOTAL_GUEST_PETS
FROM GUEST_PET;

-- 6. Count completed adoptions
SELECT COUNT(*) AS COMPLETED_ADOPTIONS
FROM ADOPTION_PROCESS
WHERE ADOPTION_STATUS = 'COMPLETED';

-- 7. Count active rescues
SELECT COUNT(*) AS ACTIVE_RESCUES
FROM RESCUE
WHERE RESCUE_STATUS = 'ACTIVE';

-- 8. Count total volunteers
SELECT COUNT(*) AS TOTAL_VOLUNTEERS
FROM VOLUNTEER;

-- 9. Calculate total completed donation amount
SELECT NVL(SUM(AMOUNT), 0) AS TOTAL_DONATION_AMOUNT
FROM DONATION
WHERE DONATION_STATUS = 'COMPLETED';

-- 10. Calculate current balance
SELECT
    NVL(
        (SELECT SUM(AMOUNT)
         FROM INCOME
         WHERE INCOME_STATUS = 'RECEIVED'),
        0
    )
    -
    NVL(
        (SELECT SUM(AMOUNT)
         FROM EXPENSE
         WHERE EXPENSE_STATUS = 'PAID'),
        0
    ) AS CURRENT_BALANCE
FROM DUAL;

-- 11. View upcoming vaccinations
SELECT
    VACCINATION_ID,
    RECORD_ID,
    VACCINE_NAME,
    VACCINATION_DATE,
    NEXT_DUE_DATE,
    VACCINATION_STATUS
FROM VACCINATION
WHERE VACCINATION_STATUS = 'SCHEDULED'
ORDER BY VACCINATION_DATE;
