-- 1. View employees with person information
SELECT
    P.PERSON_ID,
    P.NAME,
    P.PHONE_NO,
    P.EMAIL,
    E.HIRE_DATE,
    E.JOB_TITLE,
    E.EMPLOYMENT_STATUS
FROM PERSON P
JOIN EMPLOYEE E
    ON P.PERSON_ID = E.EMPLOYEE_ID
ORDER BY P.PERSON_ID;

-- 2. View pets with owner information
SELECT
    PET.PET_ID,
    PET.PET_NAME,
    PET.SPECIES,
    PET.PET_STATUS,
    P.NAME AS OWNER_NAME,
    P.PHONE_NO AS OWNER_PHONE
FROM PET
LEFT JOIN OWNER O
    ON PET.OWNER_ID = O.OWNER_ID
LEFT JOIN PERSON P
    ON O.OWNER_ID = P.PERSON_ID
ORDER BY PET.PET_ID;

-- 3. View shelter assignments with pet and shelter details
SELECT
    PET.PET_ID,
    PET.PET_NAME,
    S.SHELTER_NAME,
    SA.ASSIGN_DATE,
    SA.RELEASE_DATE
FROM SHELTER_ASSIGNMENT SA
JOIN PET
    ON SA.PET_ID = PET.PET_ID
JOIN SHELTER S
    ON SA.SHELTER_ID = S.SHELTER_ID
ORDER BY SA.ASSIGN_DATE;

-- 4. View adoption details
SELECT
    AP.ADOPTION_ID,
    PET.PET_NAME,
    ADOPTER_PERSON.NAME AS ADOPTER_NAME,
    EMPLOYEE_PERSON.NAME AS EMPLOYEE_NAME,
    AP.APPLICATION_DATE,
    AP.COMPLETION_DATE,
    AP.ADOPTION_STATUS
FROM ADOPTION_PROCESS AP
JOIN PET
    ON AP.PET_ID = PET.PET_ID
JOIN PERSON ADOPTER_PERSON
    ON AP.ADOPTER_ID = ADOPTER_PERSON.PERSON_ID
LEFT JOIN PERSON EMPLOYEE_PERSON
    ON AP.EMPLOYEE_ID = EMPLOYEE_PERSON.PERSON_ID
ORDER BY AP.ADOPTION_ID;

-- 5. View rescue details with rescued pets
SELECT
    R.RESCUE_ID,
    R.RESCUE_LOCATION,
    R.RESCUE_DATE,
    PET.PET_NAME,
    R.RESCUE_STATUS
FROM RESCUE R
JOIN RESCUE_PET RP
    ON R.RESCUE_ID = RP.RESCUE_ID
JOIN PET
    ON RP.PET_ID = PET.PET_ID
ORDER BY R.RESCUE_ID;

-- 6. View rescue volunteer details
SELECT
    R.RESCUE_ID,
    P.NAME AS VOLUNTEER_NAME,
    RV.PARTICIPATION_ROLE,
    RV.PARTICIPATION_DATE
FROM RESCUE_VOLUNTEER RV
JOIN RESCUE R
    ON RV.RESCUE_ID = R.RESCUE_ID
JOIN PERSON P
    ON RV.VOLUNTEER_ID = P.PERSON_ID
ORDER BY R.RESCUE_ID;

-- 7. View medical records with pet and doctor names
SELECT
    MR.RECORD_ID,
    PET.PET_NAME,
    P.NAME AS DOCTOR_NAME,
    MR.RECORD_DATE,
    MR.DIAGNOSIS,
    MR.TREATMENT
FROM MEDICAL_RECORD MR
JOIN PET
    ON MR.PET_ID = PET.PET_ID
JOIN PERSON P
    ON MR.DOCTOR_ID = P.PERSON_ID
ORDER BY MR.RECORD_DATE;

-- 8. View prescription details
SELECT
    PR.RECORD_ID,
    PET.PET_NAME,
    M.MEDICINE_NAME,
    PR.DOSAGE,
    PR.FREQUENCY,
    PR.DURATION_DAYS,
    PR.INSTRUCTIONS
FROM PRESCRIPTION PR
JOIN MEDICAL_RECORD MR
    ON PR.RECORD_ID = MR.RECORD_ID
JOIN PET
    ON MR.PET_ID = PET.PET_ID
JOIN MEDICINE M
    ON PR.MEDICINE_ID = M.MEDICINE_ID
ORDER BY PR.RECORD_ID;

-- 9. View donation and donor details
SELECT
    D.DONATION_ID,
    P.NAME AS DONOR_NAME,
    D.DONATION_DATE,
    D.DONATION_TYPE,
    D.AMOUNT,
    D.DONATION_STATUS
FROM DONATION D
JOIN PERSON P
    ON D.DONOR_ID = P.PERSON_ID
ORDER BY D.DONATION_DATE;

-- 10. View salary and employee details
SELECT
    S.SALARY_ID,
    P.NAME AS EMPLOYEE_NAME,
    S.SALARY_DATE,
    S.SALARY_AMOUNT,
    S.SALARY_STATUS,
    E.EXPENSE_ID
FROM SALARY S
LEFT JOIN PERSON P
    ON S.EMPLOYEE_ID = P.PERSON_ID
JOIN EXPENSE E
    ON S.EXPENSE_ID = E.EXPENSE_ID
ORDER BY S.SALARY_DATE;
