-- 1. Display person names in uppercase
SELECT
    PERSON_ID,
    UPPER(NAME) AS UPPER_NAME,
    EMAIL
FROM PERSON
ORDER BY PERSON_ID;

-- 2. Display person names in lowercase
SELECT
    PERSON_ID,
    LOWER(NAME) AS LOWER_NAME
FROM PERSON
ORDER BY PERSON_ID;

-- 3. Display pet name length
SELECT
    PET_ID,
    PET_NAME,
    LENGTH(PET_NAME) AS NAME_LENGTH
FROM PET
ORDER BY PET_ID;

-- 4. Display formatted person information
SELECT
    PERSON_ID,
    NAME || ' - ' || PHONE_NO AS PERSON_DETAILS
FROM PERSON
ORDER BY PERSON_ID;

-- 5. Display pet age in years
SELECT
    PET_ID,
    PET_NAME,
    TRUNC(MONTHS_BETWEEN(SYSDATE, DATE_OF_BIRTH) / 12)
        AS AGE_IN_YEARS
FROM PET
ORDER BY PET_ID;

-- 6. Display formatted donation amount
SELECT
    DONATION_ID,
    TO_CHAR(DONATION_DATE, 'DD-MON-YYYY') AS DONATION_DATE,
    TO_CHAR(AMOUNT, '999,999.00') AS FORMATTED_AMOUNT
FROM DONATION;

-- 7. Replace null owner name
SELECT
    PET.PET_ID,
    PET.PET_NAME,
    NVL(P.NAME, 'NO OWNER') AS OWNER_NAME
FROM PET
LEFT JOIN PERSON P
    ON PET.OWNER_ID = P.PERSON_ID
ORDER BY PET.PET_ID;

-- 8. Display next vaccination date
SELECT
    VACCINATION_ID,
    VACCINE_NAME,
    TO_CHAR(NEXT_DUE_DATE, 'DD-MON-YYYY') AS NEXT_DUE_DATE
FROM VACCINATION
WHERE NEXT_DUE_DATE IS NOT NULL
ORDER BY NEXT_DUE_DATE;

-- 9. Calculate total income
SELECT
    NVL(SUM(AMOUNT), 0) AS TOTAL_INCOME
FROM INCOME
WHERE INCOME_STATUS = 'RECEIVED';

-- 10. Calculate total expense
SELECT
    NVL(SUM(AMOUNT), 0) AS TOTAL_EXPENSE
FROM EXPENSE
WHERE EXPENSE_STATUS = 'PAID';

-- 11. Calculate average pet weight
SELECT
    ROUND(AVG(WEIGHT), 2) AS AVERAGE_PET_WEIGHT
FROM PET;

-- 12. Find highest and lowest expense
SELECT
    MAX(AMOUNT) AS HIGHEST_EXPENSE,
    MIN(AMOUNT) AS LOWEST_EXPENSE
FROM EXPENSE;
